### ISSUE TITLE
Setting "Minimum Cluster Size" to 0 and "Max Idle Minutes Before Scaledown" to 5 won't bring ASG instances number to 0

### ISSUE THREAD

**Issue by lkolchin** [jenkinsci/ec2-fleet-plugin#240] opened 2020-12-22 06:43 UTC
Hello,

I've just set up your very useful plugin but I've noticed that when I set 
"Minimum Cluster Size" to 0 and 
"Max Idle Minutes Before Scaledown" to 5 

After more than 5 minutes of inactivity the autoscaling group won't scale down to 0.

Also, documentation is not very clear on "Maximum Cluster Size" either - When is scaling up/down triggered and by what?

Using the latest plugin ver:
EC2 Fleet Jenkins Plugin 2.2.2
Jenkins 2.271

**Comment by lkolchin** [comment] 2020-12-22 06:51
Oh, I reckon there is an existing issue for this bug:

```
FleetCloud [ec2-fleet] Attempting to terminate instance: i-092cc3e3594e48926

Dec 22, 2020 6:39:15 AM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info

FleetCloud [ec2-fleet] First update not done, skip termination

Dec 22, 2020 6:39:17 AM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
```

**Comment by haugenj** [comment] 2020-12-22 18:09
Yep, this looks like a duplicate of #177

Maximum Cluster Size is the max number of instances that can belong to a Jenkins EC2FleetCloud or EC2FleetLabelCloud. It's the same idea as ASG maximum capacity - if you already have `max_number` instances in your cluster, our plugin won't try to provision any more for that Fleet/ASG. 

Jenkins runs a thread that checks for pending jobs (I think every 10 seconds by default). When there are pending jobs, Jenkins then tries to put them on an executor, but if all executors are full Jenkins will hook into our plugin and try to provision using one of the plugin's EC2Fleets. 

The Fleet doesn't immediately scale up though. It will wait until its next execution cycle to actually modify the target capacity, so if the Cloud Status Interval is long, you will see a delay in your scaling. 

Scale down is caused by nodes being idle for longer than their configured timeout. After that timeout we terminate the idle nodes and adjust the target capacity of the Fleet.

**Comment by lkolchin** [comment] 2020-12-23 00:49
@haugenj 
Thanks for clarifying this.
That makes things clearer - that also allowed me to fix the scaling to "0" issue.
Now that I know that the plugin updates DesiredCapacity in ASG, the following config worked fine for me - scaling to 0 instances worked when "Max Idle Minutes Before Scaledown"  timeout met.

ASG config:
```
  MinSize: 0
  DesiredCapacity: 1
  MaxSize: 2
```

Plugin config:
```
"Minimum Cluster Size" = 0
"Maximum Cluster Size" = 2
"Max Idle Minutes Before Scaledown" = 120
```

**Closed** 2020-12-30 01:26 UTC
Labels: duplicate
