### ISSUE TITLE
Fleet ASG fails to load

### ISSUE THREAD

**Issue by markmcnaughton** [jenkinsci/ec2-fleet-plugin#319] opened 2022-01-12 14:23 UTC
## Issue Details

**Describe the bug**
"EC2 Fleet" field fails to populate. We were previously using the same config / credentials / IAM user. The config was deleted before a Jenkins upgrade.  We also attempted to resolve by updating the plugin. We are not able to re-configure the ec2 fleet because the ASG field is not being populated (see screenshot). When exporting the config I noticed it is outputting an error (attached below in config as code section).

**To Reproduce**
1. Add a new EC2 Fleet cloud
2. Populate the required fields
3. Attempt to populate the EC2 Fleet field
4. In our case this field is not populated with known working credentials and region.

## Environment Details

**Plugin Version?**
2.4.1

**Jenkins Version?**
2.319.1

**Spot Fleet or ASG?**
ASG

**Label based fleet?**
No

**Linux or Windows?**
Linux

**EC2Fleet Configuration as Code**
``
  clouds: |-
    FAILED TO EXPORT
    hudson.model.Hudson#clouds: java.lang.LinkageError: loader constraint violation: when resolving method 'void com.amazonaws.services.autoscaling.AmazonAutoScalingClient.<init>(com.amazonaws.auth.AWSCredentialsProvider, com.amazonaws.ClientConfiguration)' the class loader hudson.PluginFirstClassLoader @d7dc458 of the current class, com/amazon/jenkins/ec2fleet/fleet/AutoScalingGroupFleet, and the class loader jenkins.util.AntClassLoader @6b04bfe0 for the method's defining class, com/amazonaws/services/autoscaling/AmazonAutoScalingClient, have different Class objects for the type com/amazonaws/auth/AWSCredentialsProvider used in the signature (com.amazon.jenkins.ec2fleet.fleet.AutoScalingGroupFleet is in unnamed module of loader hudson.PluginFirstClassLoader @d7dc458, parent loader 'app'; com.amazonaws.services.autoscaling.AmazonAutoScalingClient is in unnamed module of loader jenkins.util.AntClassLoader @6b04bfe0, parent loader 'app')
      at com.amazon.jenkins.ec2fleet.fleet.AutoScalingGroupFleet.createClient(AutoScalingGroupFleet.java:119)
      at com.amazon.jenkins.ec2fleet.fleet.AutoScalingGroupFleet.getState(AutoScalingGroupFleet.java:77)
      at com.amazon.jenkins.ec2fleet.EC2FleetCloud.<init>(EC2FleetCloud.java:218)
    Caused: java.lang.reflect.InvocationTargetException
      at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
      at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
      at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
      at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
      at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:308)
      at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$convertToNode$de0cd4f8$1(HeteroDescribableConfigurator.java:282)
      at io.vavr.CheckedFunction0.lambda$unchecked$52349c75$1(CheckedFunction0.java:247)
      at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.convertToNode(HeteroDescribableConfigurator.java:282)
      at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$describe$5(HeteroDescribableConfigurator.java:107)
      at io.vavr.control.Option.map(Option.java:392)
      at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:107)
      at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:55)
      at io.jenkins.plugins.casc.Attribute._describe(Attribute.java:328)
      at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:257)
      at io.jenkins.plugins.casc.Configurator.describe(Configurator.java:183)
``

**Anything else unique about your setup?**
no
![configure-clouds](https://user-images.githubusercontent.com/13220949/149158045-f128ac4d-8dd3-4c54-9c51-87388c1dff90.png)

**Comment by imuqtadir** [comment] 2022-01-24 18:21
Can you make sure that your AWS Creds have all the necessary permissions? From error logs, it seems that we are not able to create client for ASG which is usually the case when DescribeAutoScalingGroup permissions are missing. Also, make sure you have selected the right AWS Region.

**Comment by markmcnaughton** [comment] 2022-01-25 08:05
> Can you make sure that your AWS Creds have all the necessary permissions? From error logs, it seems that we are not able to create client for ASG which is usually the case when DescribeAutoScalingGroup permissions are missing. Also, make sure you have selected the right AWS Region.

Unfortunately, we have confirmed that the correct region is selected and that DescribeAutoScalingGroup permission is allowed.

We're using the following policy:
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeSpotFleetInstances",
                "ec2:ModifySpotFleetRequest",
                "ec2:CreateTags",
                "ec2:DescribeRegions",
                "ec2:DescribeInstances",
                "ec2:TerminateInstances",
                "ec2:DescribeInstanceStatus",
                "ec2:DescribeSpotFleetRequests"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:UpdateAutoScalingGroup"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "iam:ListInstanceProfiles",
                "iam:ListRoles",
                "iam:PassRole"
            ],
            "Resource": "*"
        }
    ]
}`

**Comment by markmcnaughton** [comment] 2022-01-25 08:06
II see this error in the Jenkins system log:

`Timer task com.amazon.jenkins.ec2fleet.CloudNanny@18adf691 failed
java.lang.LinkageError: loader constraint violation: when resolving method 'void com.amazonaws.services.autoscaling.AmazonAutoScalingClient.<init>(com.amazonaws.auth.AWSCredentialsProvider, com.amazonaws.ClientConfiguration)' the class loader hudson.PluginFirstClassLoader @3f9d5025 of the current class, com/amazon/jenkins/ec2fleet/fleet/AutoScalingGroupFleet, and the class loader jenkins.util.AntClassLoader @36501c2d for the method's defining class, com/amazonaws/services/autoscaling/AmazonAutoScalingClient, have different Class objects for the type com/amazonaws/auth/AWSCredentialsProvider used in the signature (com.amazon.jenkins.ec2fleet.fleet.AutoScalingGroupFleet is in unnamed module of loader hudson.PluginFirstClassLoader @3f9d5025, parent loader 'app'; com.amazonaws.services.autoscaling.AmazonAutoScalingClient is in unnamed module of loader jenkins.util.AntClassLoader @36501c2d, parent loader 'app')
	at com.amazon.jenkins.ec2fleet.fleet.AutoScalingGroupFleet.createClient(AutoScalingGroupFleet.java:119)
	at com.amazon.jenkins.ec2fleet.fleet.AutoScalingGroupFleet.getState(AutoScalingGroupFleet.java:77)
	at com.amazon.jenkins.ec2fleet.EC2FleetCloud.update(EC2FleetCloud.java:464)
	at com.amazon.jenkins.ec2fleet.CloudNanny.doRun(CloudNanny.java:55)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:90)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:67)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)`

**Comment by markmcnaughton** [comment] 2022-01-25 08:10
I see the user is attempting to DescribeSpotFleetRequests, but nothing about auto scaling groups 
![image](https://user-images.githubusercontent.com/13220949/150936943-465150e6-7742-400b-a4f4-bfddadf4c525.png)

**Comment by imuqtadir** [comment] 2022-01-25 16:50
I was not able to reproduce the error on my end. Can you try to add new AWSCredentials and see if that works for you? Once you do that, click on 'Test Connection` button present in the plugin settings.

**Comment by markmcnaughton** [comment] 2022-02-03 05:56
> I was not able to reproduce the error on my end. Can you try to add new AWSCredentials and see if that works for you? Once you do that, click on 'Test Connection` button present in the plugin settings.

We created a new user and provided full permissions to ASG. Unfortunately, we get the same issue.

**Comment by imuqtadir** [comment] 2022-02-07 20:25
I see that the linkage error happens when there are conflicting jars. Do you by chance are also using some other AWS EC2 plugin at the same time or have it added in your installation?

**Comment by markmcnaughton** [comment] 2022-02-08 15:47
> I see that the linkage error happens when there are conflicting jars. Do you by chance are also using some other AWS EC2 plugin at the same time or have it added in your installation?

Thanks very much. Uninstalling the EC2 plugin and re-installing the ec2-fleet-plugin resolved the issue.

**Comment by imuqtadir** [comment] 2022-02-08 15:55
Great! I'm glad that worked out. I'm resolving the issue, feel free to open new ones if you run into other issues.

**Closed by imuqtadir** 2022-02-08 15:55 UTC
Labels: bug
