### ISSUE TITLE
Add planned nodes as PlannedNode, to prevent overprovisioning.

### ISSUE THREAD

**Issue by marklagendijk** [jenkinsci/ec2-fleet-plugin#76] opened 2019-05-27 13:45 UTC
Jenkins core has nice logic for provisioning new nodes. When it is calculating the `excessWorkload` it considers the `PlannedNodes`, so it will not overprovision.

@terma commented on #53:
> I've checked Jenkins logic around provision, looks like Jenkins correctly consider planned nodes for `excessWorkload` calculation [code here](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/slaves/NodeProvisioner.java#L668), additionaly that confirmed by [article](https://support.cloudbees.com/hc/en-us/articles/115000060512-New-Shared-Agents-Clouds-are-not-being-provisioned-for-my-jobs-in-the-queue-when-I-have-agents-that-are-suspended)
> 
> My theory that we have overprovision because of incorrect adding of new nodes to Jenkins. Here [code](https://github.com/jenkinsci/ec2-fleet-plugin/blob/master/src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java#L449) how we do that now, so we add nodes directly to jenkins while it should be by `PlannedNode` [more about that](https://groups.google.com/forum/#!topic/jenkinsci-dev/SYerQ-8E-10)

I believe that a correct implementation would work as follows:

- When new nodes are created via the AWS api, they are also directly added as PlannedNode to Jenkins.
- Only when new nodes can be connected to, they are transformed to PlannedNode to normal node.

**Comment by terma** [comment] 2019-05-27 23:59
@marklagendijk, yep, plagin works in that way, hovewer I did integration testing yesterday. by somw reason jenkins is calling provision with required capacity a few times. Do you know why is that? 

In a few discusions I rwad its correct and jenkins will call you until actual capacity will not be provided, but at tge same time plugins like Dicker, VSphere dont expect tgat

**Comment by marklagendijk** [comment] 2019-05-28 08:36
@terma if Jenkins doesn't consider the PlannedNodes correctly, it might be that it doesn't know about them. Maybe we are missing some step where we register them with Jenkins?

Also, when AWS reports that nodes are there, that doesn't mean that they are ready to be used.
In our setup we run an Ansible playbook (via Rundeck) on the newly created nodes. Only after that has finished, Jenkins should start using the nodes.
At the end of the playbook, it sets up the SSH credentials for Jenkins.
So as soon as Jenkins can connect via SSH to the node, it is ready.

I think this makes sense as a general principle, and that the plugin should work like that: only when you can connect via SSH, you know that the node is ready.

**Comment by terma** [comment] 2019-05-28 15:56
Similar code:
- [EC2 provision](https://github.com/jenkinsci/ec2-plugin/blob/master/src/main/java/hudson/plugins/ec2/EC2Cloud.java#L594)
- [OpenStack provision](https://github.com/jenkinsci/openstack-cloud-plugin/blob/master/src/main/java/jenkins/plugins/openstack/compute/JCloudsCloud.java#L293)
- [vsphere provision](https://github.com/jenkinsci/vsphere-cloud-plugin/blob/master/src/main/java/org/jenkinsci/plugins/vSphereCloud.java#L323)
- [docker provision strategy](https://github.com/jenkinsci/docker-plugin/blob/master/src/main/java/io/jenkins/docker/FastNodeProvisionerStrategy.java)

Discussions:
- https://github.com/jenkinsci/docker-plugin/issues/594
- https://support.cloudbees.com/hc/en-us/articles/115000060512-New-Shared-Agents-Clouds-are-not-being-provisioned-for-my-jobs-in-the-queue-when-I-have-agents-that-are-suspended
- https://groups.google.com/forum/?nomobile=true#!searchin/jenkinsci-dev/cloud$20provision%7Csort:date/jenkinsci-dev/zO4EPrUQd7U/Xj618fjNAAAJ

**Comment by terma** [comment] 2019-05-30 18:18
I think related issue #35

**Comment by terma** [comment] 2019-05-30 18:42
Hi @marklagendijk @delgod thx a lot for reporting, it was very interesting problem to investigate.

## Investigation Result

Testing/investigation disapprove my original assumption that plugin has wrong logic about adding new nodes to Jenkins capacity. Below my current theory which already confirmed by manual testing.

### Problem

Plugin creates planned nodes (nodes which requested from EC2 Spot) as expected. Plugin convert planned nodes to real as soon as it can describe them by EC2 API ```describeInstance```. Which doesn't mean that node is actually ready for SSH or any other Jenkins connection. As result Jenkins first try to connect is failed and node assumed as offline with retry, so eventyally they will be online.  At the same time Jenkins default strategy is trying to provision more capacity as not enough online, however it doesn't consider ```offline``` nodes so it requests plugin to provision same/less capacity more and more time until nodes will be online.

### Possible solutions

#### Option 1

Consider instance state during ```describeInstance``` call and don't convert planned node into real until state will not be ```running```

Easy todo and small impact onto current logic, however it doesn't solve problem if OS boot time is big, so from EC2 point of view instance will be ```running``` but Jenkins will not be able to SSH

I didn't find clear documentation about ```running``` so need some additional reseach

#### Option 2

Implement own strategy to consider ```ofline``` nodes as capacity and don't request more

Should cover all delay during node start, however if you have bad instance which cannot be ```online``` Jenkins will not request more automatically as it does currently, in fact we can ask plugin users to use health check for their fleets, however it's additional work on their side

Other options are welcome, I will think more about best option.

**Comment by delgod** [comment] 2019-05-31 06:20
Hi Artem,

I more care about shutdown logic, when instance with running job is killed on fleet downscale

**Comment by terma** [comment] 2019-05-31 08:32
@delgod, ok, I'm done with this one, next one will be shutdown

**Comment by marklagendijk** [comment] 2019-05-31 12:19
@terma 
Just read your comment, and glanced a bit at your commit. I would like to react on both.

About option 1 you write:
>Easy todo and small impact onto current logic, however it doesn't solve problem if OS boot time is big, so from EC2 point of view instance will be running but Jenkins will not be able to SSH

I think this is an important point. If I understand everything correctly the 'status check' will only help for cases where the nodes are directly available after the status is `running`.

I would propose the following, I'm not sure how hard this will be to implement.

**Option 3**

- We wait the new node to become available, as we are already doing now.
- As soon as the node is available (so we know its IP address) we add it to a separate collection `bootingNodes`.
- For every item the `bootingNodes` collection we try to establish an SSH connection. Only as soon as it succeeds we change the node into a real node.


Small comment on your commit: I saw that you made your change optional. Is there any reason why this should be optional? Shouldn't it be default, non-configurable behavior? Are there any downsides to it?

**Comment by terma** [comment] 2019-05-31 16:26
hi @marklagendijk, option 1 is released under version [1.4.0](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-1.4.0) for now it should be explicitly enabled in cloud configuration (at the end). 

It's optional because of two reasons: first, just want to get feedback first before applying it all users, second it the possible case, when a particular node cannot start and if you don't configure health check for your EC2 Spot Fleet old version of plugin, will mark it as offline and Jenkins will try to request one more node if capacity is not full, with this fix Jenkins will not request more capacity and will wait until this node will be fixed.

Let's see if that approach works, and we can decide future actions.

**Comment by sdhoka** [comment] 2019-06-11 23:16
@terma 
Thanks for contributing this plugin to the open source community. I'd like to provide some feedback based on my usage of 1.5.0 of the plugin. For my use case, I am using amazon_linux images and the plugin often over-provisions by 2-3 nodes even when the `Only running instances` option has been enabled. As you pointed out in the thread above,  it might be because the plugin doesn't wait for the os to boot. 

Adding to your list of solutions, I'm thinking that maybe we can have a field for the user to provide boot delay(ec2-plugin has similar option) and wait for the delay time before considering it as offline and provisioning new nodes. Let me know your thoughts on if this could be a short term fix to the issue

**Comment by terma** [comment] 2019-06-12 01:00
@sdhoka thx for feedback, I think delay time is good short term option plus its relative simple and no impact for existent clients. If you have time to contribute it, always welcome or I can try to find time.

btw, did you see any improvements with "only running instances" enabled?

**Comment by marklagendijk** [comment] 2019-06-12 11:19
This would indeed be a great step forwards!
Although I still believe checking whether Jenkins can connect via SSH would be the best check, the delay option would probably be much easier to implement, and be already a great improvement over the current situation.

**Comment by sdhoka** [comment] 2019-06-17 15:56
> @sdhoka thx for feedback, I think delay time is good short term option plus its relative simple and no impact for existent clients. If you have time to contribute it, always welcome or I can try to find time.
@terma sadly, I'm not very familiar with Jenkins plugin development. I can definitely start learning but it might take some time to fix.
> btw, did you see any improvements with "only running instances" enabled?
I recently started using the ec2-fleet plugin, starting with 1.5.0, I'm running into over-provisioning issues but haven't got a chance to compare it with previous versions

**Comment by terma** [comment] 2019-06-18 04:35
@sdhoka nw, I can do that, thx for info.

**Comment by terma** [comment] 2019-06-22 06:06
Testing approach to try ssh node before making it available for Jenkins, EC2 plugin [code example](https://github.com/jenkinsci/ec2-plugin/blob/master/src/main/java/hudson/plugins/ec2/EC2Cloud.java#L640)

**Comment by terma** [comment] 2019-07-02 05:10
Fix released under version [1.8.0](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-1.8.0)

**Comment by marklagendijk** [comment] 2019-07-03 14:36
Tested [1.8.1](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-1.8.1) and it is a huge improvement over the previous situation.
Jenkins is no longer over provisioning nodes, while still keeping up properly with the queue.

**Comment by terma** [comment] 2019-07-03 15:34
Thx for the feedback. 

Answer. Yes, that's correct. 

Two reasons for that:
- if the plugin doesn't add a node to Jenkins it almost impossible to use SSH connection, as it really depends on fact that slave/node in Jenkins
- I think adding node immediately as offline is better than hide them, as Jenkins user can see actual situation, instead of guessing do I really have some nodes from the fleet or not.

Btw, if you think it could be useful we can override node/slave display node to represent fact that node in init process, we can do that even for icon =)

**Comment by marklagendijk** [comment] 2019-07-03 16:42
An different icon would be very cool! The current icon looks like there is something wrong. If we can use an icon that better reflects that the node is starting, that would be a big improvement.

**Comment by terma** [comment] 2019-07-03 16:53
ok, create issue for that #113 you can plus it =)

**Comment by terma** [comment] 2019-07-05 17:59
I'm closing issue as fixed, feel free to comment/reopen if any problem. thx everyone for help with testing and suggestions.

**Closed by terma** 2019-07-05 17:59 UTC
Labels: enhancement
