### ISSUE TITLE
Plugin doesnt scale down

### ISSUE THREAD

**Issue by pedersen2Elsevier** [jenkinsci/ec2-fleet-plugin#177] opened 2020-03-27 06:41 UTC
I have an issue where the plugin doesnt scale down again.

Currently i have 39 spot nodes runnig, all being idle for about 10 hours.

I see alot of this in the log: 

2020-03-27 06:14:38.621+0000 [id=40]	INFO	c.a.j.e.IdleRetentionStrategy#check: Check if node idle i-005c6f57cefd22a24
2020-03-27 06:14:38.621+0000 [id=40]	INFO	c.a.j.e.IdleRetentionStrategy#isIdleForTooLong: Instance: Jenkins Spot Fleet i-005c6f57cefd22a24 Age: 35588212 Max Age:60000
2020-03-27 06:14:38.621+0000 [id=40]	INFO	c.a.j.ec2fleet.EC2FleetCloud#info: Jenkins Spot Fleet [Xxx] Attempting to terminate instance: i-005c6f57cefd22a24
2020-03-27 06:14:38.621+0000 [id=40]	INFO	c.a.j.ec2fleet.EC2FleetCloud#info: Jenkins Spot Fleet [XXX] First update not done, skip termination

Which according to the code happens when   if (stats == null)

is this a bug or something i might have misconfigured? i am currently using version 2.0.0 of the plugin.

**Comment by v3se** [comment] 2020-04-01 07:38
Hi, we have the exact same issue with the 2.0.0 version of the plugin:

`2020-04-01 05:11:29.883+0000 [id=60]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-spot-fleet] Attempting to terminate instance: xxxxxx                                                                                   2020-04-01 05:11:29.883+0000 [id=60]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-spot-fleet] First update not done, skip termination`

Jenkins restart seems to solve it temporarily.

**Comment by terma** [comment] 2020-04-01 16:54
Thx for config, let me try to reproduce, seems like bug

**Comment by terma** [comment] 2020-04-01 16:55
Do you see in logs any errors or messages from plugin smt like ```start``` should happens on regular basis like once per ```15 sec``` depends on your settings.

**Comment by v3se** [comment] 2020-04-02 08:44
I can see these messages regularly in jenkins.log:

`2020-04-02 08:37:57.542+0000 [id=58]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-spot-fleet] start `

And no errors related to the plugin.  Currently I'm also having an issue with the fleet scaling up properly although I have many jobs in queue. I can see that it can modify the spot fleet but very slowly. Don't know if its related to this.

**Comment by v3se** [comment] 2020-04-07 07:01
The same issue occurred on a different Jenkins instance now.

`2020-04-07 06:39:25.168+0000 [id=50]    INFO    c.a.j.e.IdleRetentionStrategy#isIdleForTooLong: Instance: FleetCloud i-0d4f2c83f49743609 Age: 720000 Max Age:600000
2020-04-07 06:39:25.168+0000 [id=50]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-spot-fleet] Attempting to terminate instance: i-0d4f2c83f49743609
2020-04-07 06:39:25.168+0000 [id=50]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-spot-fleet] First update not done, skip termination
`
Both are running Jenkins version 2.204.1.

**Comment by cw-pratik** [comment] 2020-04-08 13:29
I Just installed the plugin and am giving it a try. I think I am also facing the same issue. The instances are not downscaling.

I am running Jenkins version 2.190.1

I noticed one thing. There was instance scale in protection enabled for all the instances that came up. Is it intentional?

```2020-04-08 13:24:13.559+0000 [id=51]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: LinuxFleet [linux-test] start
2020-04-08 13:24:13.649+0000 [id=51]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: LinuxFleet [linux-test] fleet instances [i-00eb137572674c478, i-0fe90f05fd44b9981]
2020-04-08 13:24:13.689+0000 [id=51]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: LinuxFleet [linux-test] described instances [i-00eb137572674c478, i-0fe90f05fd44b9981]
2020-04-08 13:24:13.689+0000 [id=51]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: LinuxFleet [linux-test] jenkins nodes [i-00eb137572674c478, i-0fe90f05fd44b9981]
2020-04-08 13:24:13.689+0000 [id=51]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: LinuxFleet [linux-test] jenkins nodes without instance []
2020-04-08 13:24:13.689+0000 [id=51]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: LinuxFleet [linux-test] terminated instances []
2020-04-08 13:24:13.689+0000 [id=51]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: LinuxFleet [linux-test] new instances []
2020-04-08 13:24:13.886+0000 [id=49]    INFO    c.a.j.e.IdleRetentionStrategy#check: Check if node idle i-00eb137572674c478
2020-04-08 13:24:13.886+0000 [id=49]    INFO    c.a.j.e.IdleRetentionStrategy#check: Check if node idle i-0fe90f05fd44b9981
```

This is the only logs I get.

Am using AutoScaling groups here.

**Comment by pcantea** [comment] 2020-04-13 16:29
Same issue here, nodes are not scaled down when idle for longer than the idle setting. The nodes are just marked as suspended, but Jenkins won't reconnect to them, causing new nodes to come up when new jobs are added to the queue.

```
ec2-fleet [ec2-spot-fleet] start

Apr 13, 2020 4:26:50 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info

ec2-fleet [ec2-spot-fleet] fleet instances [i-063d81d3b0aafc626, i-0cec7f55132e399f9, i-09da2f9b7f97b8728]

Apr 13, 2020 4:26:50 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info

ec2-fleet [ec2-spot-fleet] described instances [i-063d81d3b0aafc626, i-0cec7f55132e399f9, i-09da2f9b7f97b8728]

Apr 13, 2020 4:26:50 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info

ec2-fleet [ec2-spot-fleet] jenkins nodes [i-063d81d3b0aafc626, i-0cec7f55132e399f9, i-09da2f9b7f97b8728]

Apr 13, 2020 4:26:50 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info

ec2-fleet [ec2-spot-fleet] jenkins nodes without instance []

Apr 13, 2020 4:26:50 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info

ec2-fleet [ec2-spot-fleet] terminated instances []

Apr 13, 2020 4:26:50 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info

ec2-fleet [ec2-spot-fleet] new instances []

Apr 13, 2020 4:27:42 PM INFO com.amazon.jenkins.ec2fleet.IdleRetentionStrategy check

Check if node idle i-063d81d3b0aafc626

Apr 13, 2020 4:27:42 PM INFO com.amazon.jenkins.ec2fleet.IdleRetentionStrategy isIdleForTooLong

Instance: ec2-fleet i-063d81d3b0aafc626 Age: 431946 Max Age:1800000

Apr 13, 2020 4:27:42 PM INFO com.amazon.jenkins.ec2fleet.IdleRetentionStrategy check

Check if node idle i-09da2f9b7f97b8728

Apr 13, 2020 4:27:42 PM INFO com.amazon.jenkins.ec2fleet.IdleRetentionStrategy isIdleForTooLong

Instance: ec2-fleet i-09da2f9b7f97b8728 Age: 152204 Max Age:1800000

Apr 13, 2020 4:27:42 PM INFO com.amazon.jenkins.ec2fleet.IdleRetentionStrategy check

Check if node idle i-0cec7f55132e399f9

Apr 13, 2020 4:27:42 PM INFO com.amazon.jenkins.ec2fleet.IdleRetentionStrategy isIdleForTooLong

Instance: ec2-fleet i-0cec7f55132e399f9 Age: 233666964 Max Age:1800000

Apr 13, 2020 4:27:42 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info

ec2-fleet [ec2-spot-fleet] Attempting to terminate instance: i-0cec7f55132e399f9

Apr 13, 2020 4:27:50 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info

ec2-fleet [ec2-spot-fleet] start

Apr 13, 2020 4:27:50 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info

ec2-fleet [ec2-spot-fleet] fleet instances [i-063d81d3b0aafc626, i-0cec7f55132e399f9, i-09da2f9b7f97b8728]

Apr 13, 2020 4:27:50 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info

ec2-fleet [ec2-spot-fleet] described instances [i-063d81d3b0aafc626, i-0cec7f55132e399f9, i-09da2f9b7f97b8728]

Apr 13, 2020 4:27:50 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info

ec2-fleet [ec2-spot-fleet] jenkins nodes [i-063d81d3b0aafc626, i-0cec7f55132e399f9, i-09da2f9b7f97b8728]

Apr 13, 2020 4:27:50 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info

ec2-fleet [ec2-spot-fleet] jenkins nodes without instance []

Apr 13, 2020 4:27:50 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info

ec2-fleet [ec2-spot-fleet] terminated instances []

Apr 13, 2020 4:27:50 PM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info

ec2-fleet [ec2-spot-fleet] new instances []

```

**Comment by v3se** [comment] 2020-04-22 07:08
@pcantea I'm seeing this behavior as well but not sure if its related to this because you don't have the `First update not done, skip termination` message in your logs.

We handled the hanging slaves with the suspended label by creating a scheduled Jenkins job to clean them out. I'm not sure if that will mess things up. I'm seeing that overtime the fleet scales up much poorly. 

![auto-scale-issue](https://user-images.githubusercontent.com/44093205/79951254-06ec0480-8481-11ea-8bb7-86e0b4003da3.PNG)

I'm wondering if this cleaning job we created will affect the calculations used for provisioning new slaves?

**Comment by bigbohne** [comment] 2020-04-27 09:58
Hint from my side:
We use the ec2-fleet plugin in our company for quote some time now ... no problems.

We started to observe this bug directly after enabling the "No Delay Provision Strategy" option.

Hope this helps

**Comment by yuri-1987** [comment] 2020-05-02 20:51
> Hint from my side:
> We use the ec2-fleet plugin in our company for quote some time now ... no problems.
> 
> We started to observe this bug directly after enabling the "No Delay Provision Strategy" option.
> 
> Hope this helps

same here, after enabling "No Delay Provision Strategy" nodes are not scaled in anymore.

**Comment by terma** [comment] 2020-05-25 23:25
Trying to reproduce this case. Based on current code I can image very exotic case when plugin configuration was updated and while plugin has some nodes. Plugin has logic to correctly move nodes to new configuration, however it very depends on Jenkins.

A few questions:
1. if some one can share full Jenkins logs for example for last 10 min when this issue occurs (only plugin related logs is required)
1. how do you configure plugin, UI, from pipe, smt else?
1. what happened before this issue? Any recent plugin settings update? Some other configuration changes?

thx

**Comment by danielfariati** [comment] 2020-09-12 01:18
This is happened multiple times to us as well.
Apparently, this happens after we change the plugin configuration with instances already running.

To solve it, we stop all running pipelines, then we go to AWS console and change the capacity of all fleets to zero manually... Then, it starts to work as expected again.

I haven't looked at the code, but maybe this information gives some insight of what is the problem.

Unfortunately I don't have any logs right now, as this last happened some time ago.
If it ever happens again (and this is not solved yet), I'll post the logs here...

**Comment by amainwaring** [comment] 2020-09-29 12:05
I'm also having a similar issue using an ASG and nodes not scaling down correctly. I've found that at some point the ASG config gets reset to enable scale-in protection and then the nodes won't scale down. I reset the ASG config to disable scale-in protection and remove it from the ASG instances themselves, but at some point the ASG gets reset to enable scale-in protection and it won't scale down correctly after that.

I'm using the UI to configure the plugin (v2.1.3) with a manually created ASG. Any help would be appreciated! Thanks!

**Comment by amainwaring** [comment] 2020-09-30 12:46
I've done some more digging this morning and it seems like it still isn't scaling down quite properly. I am trying to have the scale-in trigger an SNS->Lambda->Jenkins job to remove the scaled-in worker from AD/DNS. What I am finding is that by the time the Lambda runs the instance has already been terminated.

![image](https://user-images.githubusercontent.com/20444883/94686580-080b4280-02f9-11eb-8751-078e79ed15c1.png)
![image](https://user-images.githubusercontent.com/20444883/94686691-2bce8880-02f9-11eb-93d7-7b2fcdb6b979.png)

I think what is happening is that the ec2-fleet plugin is terminating the instance, but I think instead it should be removing the scale-in protection from the instance and letting the ASG terminate it.

> 
> edit: Nevermind my issue, I understand now that the plugin works via the scale-in protection so that a used node doesn't accidentally get taken out of the load. My issue was with a Lambda that I had triggering when the machine was shut down was checking for the instance state and not running since the instance had already been terminated. The plugin is working well scaling up/down now!
> 
> I'm also having a similar issue using an ASG and nodes not scaling down correctly. I've found that at some point the ASG config gets reset to enable scale-in protection and then the nodes won't scale down. I reset the ASG config to disable scale-in protection and remove it from the ASG instances themselves, but at some point the ASG gets reset to enable scale-in protection and it won't scale down correctly after that.
> 
> I'm using the UI to configure the plugin (v2.1.3) with a manually created ASG. Any help would be appreciated! Thanks!

**Comment by imuqtadir** [comment] 2020-09-30 17:08
@amainwaring Are you seeing this error:

`2020-03-27 06:14:38.621+0000 [id=40] INFO c.a.j.ec2fleet.EC2FleetCloud#info: Jenkins Spot Fleet [XXX] First update not done, skip termination
`
I think your issue is different and you should probably create a new issue for this so we can investigate it further.

**Comment by amainwaring** [comment] 2020-09-30 17:10
Sorry, good point. My issue is different and I will create a new issue. Thanks!

**Comment by gaforester** [comment] 2020-11-18 15:33
Did anyone ever find a solution for this? I'm having the issue as well. I've downgraded, upgraded, created new fleets, removed plugin and re-installed, deleted clouds and re-created, and restarted Jenkins about 100 times. Still same issues. I still get the `First update not done, skip termination` no matter what I do. Still won't scale down.

**Comment by lkolchin** [comment] 2020-12-22 06:50
Using the plugin with ASG and seem to be hitting the same issue:
```
FleetCloud [ec2-fleet] Attempting to terminate instance: i-092cc3e3594e48926

Dec 22, 2020 6:39:15 AM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info

FleetCloud [ec2-fleet] First update not done, skip termination

Dec 22, 2020 6:39:17 AM INFO com.amazon.jenkins.ec2fleet.EC2FleetCloud info
```

Did anyone found a way to resolve it?

**Comment by kino505** [comment] 2020-12-24 10:20
I found that the EC2 Fleet plugin always set special options for ASG: Advanced configurations -> Instance scale-in protection.
I have tried to off this setting but the plugin always turns on again. 
The "No Delay Provision Strategy" option does not matter.

**Comment by imuqtadir** [comment] 2020-12-29 18:06
@kino505 This is expected behavior of the plugin. Without scale-in protection, ASG could randomly terminate EC2 instances. We need to enable this so that the plugin could decide which ones to terminate.

**Comment by imuqtadir** [comment] 2020-12-29 18:10
@lkolchin It would be helpful if you could answer these questions:

1. I understand that this issue revolves around instances not being terminated. However, this thread is also responsible for provisioning. Are you able to provision/scale up more instances when you encounter this issue?
2. Do you see `start` within your logs? This should show up every Cloud Status Interval in sec. This value is set within your plugin settings (by default 15 seconds). Can you share more logs around this?
3. Do you notice any deadlock or any useful info within your thread dump while this issue is happening? You can check your thread dump here under /threadDump ex: http://localhost:5005/jenkins/threadDump
4. Did this issue happen after you changed any particular setting? Like changing ASG etc. 

Any steps to help replicate this would be helpful.

**Comment by lkolchin** [comment] 2020-12-30 01:25
@imuqtadir 

I reckon the problem is really a lack of comprehensive documentation.
Now that @haugenj clarified this for me at https://github.com/jenkinsci/ec2-fleet-plugin/issues/240

I know now that the plugin updates DesiredCapacity in ASG, the following config worked fine for me - scaling to 0 instances worked when "Max Idle Minutes Before Scaledown" timeout met.

ASG config:
```
  MinSize: 0
  DesiredCapacity: 1
  MaxSize: 2
```
Plugin config:
```
"Minimum Cluster Size" = 0
"Maximum Cluster Size" = 2
"Max Idle Minutes Before Scaledown" = 120
```

**Comment by imuqtadir** [comment] 2020-12-30 19:33
@lkolchin Good to hear it is resolved. I agree we can add more documentation around the plugin settings. Feel free to create an issue around it.

**Comment by lloydchang** [comment] 2021-01-01 00:11
Hi, @terma and @imuqtadir,

Summary:
• Issue recurs: scale in of EC2 Spot Fleet Request scale in pauses after a threshold
• Scale in pausing threshold is same number of Jenkins jobs that I had started a build
• ec2-fleet-plugin scale out dynamically by setting target capacity at the number of Jenkins job that I had started
• ec2-fleet-plugin doesn't scale in dynamically by setting target capacity at minimum cluster size after nodes are idle
• In this context, "scale down" is also known as scale in, as in scaling in and scaling out horizontally, by the number of EC2 Spot Instances

Details:

In my experience, the scale in pausing threshold is at the same number of different Jenkins jobs that I had started:
• In 1 hour, I started builds of 20 different Jenkins jobs, and ec2-fleet-plugin provisioned upwards of 40 EC2 Spot Fleet instances in 1 hour
• Scaling upwards of 40 (40 out of 100 maximum cluster size) makes sense to me because I enabled No Delay Provision Strategy
• After 13 of the 20 different Jenkins jobs completed, the ec2-fleet-plugin started to scale in slowly... 1 at a time... from 40, 39, 38, 37, etc., until it reached a scale in pausing threshold of 20
• This scale in pausing threshold of 20 — happens to be the same number 20 — I had started builds of 20 different Jenkins jobs
• At this point, the plugin doesn't scale in anymore
• I need to implement two workarounds; see below:

I'm using EC2 Fleet plugin 2.2.0, Jenkins 2.222.3

I noticed the two contributing factors:
1. ec2-fleet-plugin sets `excess-capacity-termination-policy` of `no-termination` even though https://github.com/jenkinsci/ec2-fleet-plugin/pull/154 was closed via https://github.com/jenkinsci/ec2-fleet-plugin/pull/154/commits/26768abed774266b0a39ad7522e574a4a62871d6
2. ec2-fleet-plugin scale in pauses after a threshold — scale in pausing threshold is at the same number of builds that I had started

---

Here are my two workaround, combined, for the contributing two factors:

Workaround 1 — Enforce `--excess-capacity-termination-policy default`

Depending on circumstances: Either `@hourly`, or `@daily`, or `@weekly` — I schedule a Jenkins job executing:

```
#!/bin/bash -x
aws ec2 describe-spot-fleet-requests
aws ec2 describe-spot-fleet-requests --query 'SpotFleetRequestConfigs[].SpotFleetRequestConfig[].ExcessCapacityTerminationPolicy'
for REQUEST_ID in $(aws ec2 describe-spot-fleet-requests \
  --query 'SpotFleetRequestConfigs[*].SpotFleetRequestId' --output text); \
  do aws ec2 modify-spot-fleet-request \
  --excess-capacity-termination-policy default \
  --spot-fleet-request-id $REQUEST_ID; \
done
aws ec2 describe-spot-fleet-requests
aws ec2 describe-spot-fleet-requests --query 'SpotFleetRequestConfigs[].SpotFleetRequestConfig[].ExcessCapacityTerminationPolicy'
```
to describe the spot fleet requests, iterate through all spot fleet requests (fulfilled, canceled, etc.) to try setting ExcessCapacityTerminationPolicy to default, then describe the spot fleet requests again.

Workaround 2 — Configure EC2 Spot Fleet's Auto Scaling feature to scale in further, below the scale in pausing threshold (20)...

After the scale in pausing threshold of 20 (same number as the number of Jenkins jobs that I had started)... I had to configure EC2 Spot Fleet's Auto Scaling feature to scale in further, below the scale in pausing threshold (20).

In my EC2 Spot Fleet Request, I configured Auto Scaling:

**Auto Scaling**
Scale capacity between: 2 and 100 Instances
IAM role for fleet Auto Scaling: AWSServiceRoleForApplicationAutoScaling_EC2SpotFleetRequest
**Scaling policies**
Policy type: Target tracking policy
Policy name: Scale fleet to target
Target metric: Average CPU Utilization
Target value: 100 (this is 100 as in 100% CPU utilization, which is overly aggressive; depending on circumstances, I change this value from 100 to either default of 50, or 30, or 20 depending on how aggressive this should be when scaling in)
Cooldown period: 1 (this is 1 to be aggressive; enhanced monitoring is off, thus CloudWatch captures metrics at default intervals of 5 minutes)
Disable scale-in: no

---

If you want to reproduce the issue, here are relevant configuration values for ec2-fleet-plugin:

Region: us-west-2 US West (Oregon)
EC2 Fleet: EC2 Spot Fleet - sfr-...-...-...-... (active) (maintain)
Number of Executors: 1
Scale Executors by Weight: [ ] (Not checked at all)
Max Idle Minutes Before Scaledown: 1
Minimum Cluster Size: 2
Maximum Cluster Size: 100
Disable build resubmit:  [ ] (Not checked at all)
Maximum Init Connection Timeout in sec: 180
Cloud Status Interval in sec: 10
No Delay Provision Strategy: checked to leverage https://github.com/jenkinsci/ec2-fleet-plugin/pull/142

If you want to reproduce the issue, here are relevant configuration values for EC2 Spot Fleet Request:

**Request ID: sfr-...-...-...-...**
**Description**
Request ID: sfr-...-...-...-...
Max price: -
Request type: fleet
Persistence: maintain
Created: ##/##/####, ##:## am/pm
Key pair name: -
State: active
IAM role: -
Status: fulfilled
EBS-optimized: no
Total target capacity: ## (## fulfilled)
Monitoring: no
On-Demand capacity: 0 (0 fulfilled)
Tenancy: default
Allocation strategy: capacityOptimized
Interruption behavior: terminate
Instance type(s): m5zn.xlarge weight=1
Classic load balancers: -
AMI ID: -
Target Groups: -
Subnet: subnet-..., subnet-..., subnet-... (only 3 out of 4 subnets in us-west-2 Oregon supports m5zn.xlarge)
Request valid from: ##/##/####, ##:## am/pm
IAM fleet role: aws-ec2-spot-fleet-tagging-role 
Request valid until: ##/##/####, ##:## am/pm
Terminate instances at expiration: no
Launch template: lt-... ver.##
Capacity rebalance: -
Instance replacement strategy: -

**Auto Scaling**
Scale capacity between: 2 and 100 Instances
IAM role for fleet Auto Scaling: AWSServiceRoleForApplicationAutoScaling_EC2SpotFleetRequest
**Scaling policies**
Policy type: Target tracking policy
Policy name: Scale fleet to target
Target metric: Average CPU Utilization
Target value: 100 (this is 100 as in 100% CPU utilization, which is overly aggressive; depending on circumstances, I change this value from 100 to either default of 50, or 30, or 20 depending on how aggressive this should be when scaling in)
Cooldown period: 1 (this is 1 to be aggressive; enhanced monitoring is off, thus CloudWatch captures metrics at default intervals of 5 minutes)
Disable scale-in: no

---

Thank you @terma and @imuqtadir

**Comment by imuqtadir** [comment] 2021-01-06 15:55
I'm able to replicate this bug. It has nothing to do with the configuration however it occurs when you change existing settings of the plugin (eg. numOfExecutors). I'm working on a fix for this now.

**Comment by imuqtadir** [comment] 2021-01-08 19:08
I'll cut a release next week once I get approval on my PR.

**Comment by lloydchang** [comment] 2021-01-10 05:58
Thank you @imuqtadir

**Comment by lloydchang** [comment] 2021-01-11 01:34
@imuqtadir Thank you for upcoming cutting a release with a bug fix.

Would you know if the Jenkins version would make any difference at all when you reproduced the bug?

Coincidentally, for what it's worth, I recently upgraded...
from EC2 Fleet plugin 2.2.0, Jenkins 2.222.3 (2020-04-24)
to EC2 Fleet plugin 2.2.0, Jenkins 2.263.1 (2020-12-03)
and I noticed the bug's frequency decreased.

With that said, it could be coincidental.

**Closed** 2021-01-11 15:54 UTC
Labels: bug
