### ISSUE TITLE
"removing fleet node" items in nodes section

### ISSUE THREAD

**Issue by romang12** [jenkinsci/ec2-fleet-plugin#122] opened 2019-07-17 14:02 UTC
Hi,
I have this strange issue: 
after some time instances with name "removing fleet node" appear in node section.

![image](https://user-images.githubusercontent.com/19771895/61381907-714d9400-a8b4-11e9-8e15-869cc643f019.png)

And they do not disappear until I remove them manually.

**Comment by terma** [comment] 2019-07-17 18:57
wow, interesting, Jenkins internally represent each slave as two parts ```Computer``` and ```Node``` usually this case happens when slave in the middle of removing process, so ```Node``` removed, but ```Computer``` still present.

Do you see any particular condition when that happens? Did you do reconfiguration just before?

**Comment by romang12** [comment] 2019-07-18 14:32
@terma Hi,
Nothing was reconfigured before.
Today I've restarted Jenkins service of Master. Since that I haven't seen this issue.
Will keep you in touch in case of issue occurs again.

**Comment by terma** [comment] 2019-07-18 15:29
thx in meanwhile will try to reproduce

**Comment by romang12** [comment] 2019-07-22 17:15
@terma Hi Artem,

One more strange issue: Slave seems ok, but according Executor status it's dead

![image](https://user-images.githubusercontent.com/19771895/61650793-1ef9e200-acbd-11e9-9eb3-b3ed49d3d7ba.png)

But if I see its log, it's alive:

<===[JENKINS REMOTING CAPACITY]===>channel started
Slave.jar version: 2.52
This is a Unix slave
Evacuated stdout
Slave successfully connected and online
log4j:WARN No appenders could be found for logger (org.apache.commons.beanutils.converters.BooleanConverter).
log4j:WARN Please initialize the log4j system properly.
Jul 22, 2019 12:08:43 PM com.amazonaws.services.s3.internal.S3V4AuthErrorRetryStrategy buildRetryParams
WARNING: Attempting to re-send the request to dev-ci.s3.eu-central-1.amazonaws.com with AWS V4 authentication. To avoid this warning in the future, please use region-specific endpoint to access buckets located in regions that require V4 signing.

**Comment by terma** [comment] 2019-07-25 16:12
wow never saw that, let check

**Comment by imuqtadir** [comment] 2021-01-15 16:00
Is the issue still happening in the latest release?

**Comment by imuqtadir** [comment] 2021-01-19 20:56
Closing the issue due to staleness. Please create a new one if this continues to happen in latest releases.

**Closed by imuqtadir** 2021-01-19 20:56 UTC
