### ISSUE TITLE
Resubmitted jobs lose their parameters

### ISSUE THREAD

**Issue by Liath** [jenkinsci/ec2-fleet-plugin#120] opened 2019-07-11 02:53 UTC
It looks like build parameters are lost when a job is resubmitted due to SpotFleet killing the host it was running on.

It's kind of uninteresting but, just in case, here is the log: https://gist.github.com/Liath/bba5290f1bf0665ee61d6ccd1fc3020e

The Jenkinsfile of the job is something like this:
```
pipeline {
  agent {
    label "ec2-fleet"
  }

  parameters {
    string(name: 'template', defaultValue: 'false', description: 'a path')
    string(name: 'stage', defaultValue: 'dev', description: 'environment')
  }

  stages {
    stage('Build') {
      when { expression { params.template != 'false' } }

      steps {
        withAWS(region: 'us-west-2', credentials: 'aws') {
          sh "long-running --stage ${params.stage}' ${params.template}"
        }
      }
    }
  }
}
```

**Comment by terma** [comment] 2019-07-12 15:56
thx for report, let me check

**Comment by imuqtadir** [comment] 2020-08-17 18:40
@Liath I tried to replicate this bug. Steps:

1. Started a parametrized build on instance
2. The build starts executing
3. Terminate the instance abruptly
4. Build gets resubmitted
5. New instance picks up the build.

However, I do see the parameters were also passed and not lost. I would need more details here for reproducing this bug.

**Comment by imuqtadir** [comment] 2020-08-26 19:46
I'm closing this for now. Please let us know if this is still the issue and reopen it.

**Closed by imuqtadir** 2020-08-26 19:46 UTC
Labels: bug

**Comment by Liath** [comment] 2020-12-28 20:34
Just saw this, sorry about the delay. I no longer use Jenkins so don't have an easy way to reproduce what I was seeing anymore. Thanks for taking a look though!

**Comment by mfa-inverso** [comment] 2021-04-15 16:33
For me this does also not work. Perhaps it's a problem with pipeline jobs. 
Build 10 has parameters:
![image](https://user-images.githubusercontent.com/62642310/114905011-c36c7200-9e18-11eb-884c-b5eeeda972ec.png)
Build 11 is the resceduled build after I terminated the instance and it has no parameters:
![image](https://user-images.githubusercontent.com/62642310/114905069-d4b57e80-9e18-11eb-96af-cc040f41b391.png)
There even isn't a parameters section in the menu. It also fails because the parameters are not set. 
Perhaps it works sometimes because the default values for the parameters are used.
