### ISSUE TITLE
Huge lag in provisioning workers, workers become suspended but not deleted

### ISSUE THREAD

**Issue by wosiu** [jenkinsci/ec2-fleet-plugin#322] opened 2022-02-08 19:42 UTC
## Issue Details

Sometimes there is a huge lag before workers are provisioned. Our developers started to observe this few weeks ago.
So for example:
```
16:36:56  Still waiting to schedule task
16:36:56  All nodes of label ‘[integration-tests&&spot&&disable-resubmit](https://anonymised.it/label/integration-tests&&spot&&disable-resubmit/)’ are offline
18:16:54  Running on [ci-jenkins-executor--integration-tests-spot i-0fda2dca2c245b03a](https://anonymised.it/computer/i-0fda2dca2c245b03a/) in /mnt/jenkins/workspaces/workspace/sanity-check-on-stag
```
As you can see the machine was provisioned almost 2 hours later. And I guess it started only because we manually changed a minimum cluster size for this label to 1 to kinda kick it.

I don't have full log, but I was able to collect some logs from this period of time while the build was waiting for a node:
```
2022-02-08 16:45:42.495+0000 [id=42]  FINE  c.amazon.jenkins.ec2fleet.EC2FleetCloud: ci-jenkins-executor--integration-tests-spot [ integration-tests spot disable-resubmit 1executors] setting stats
2022-02-08 16:45:42.495+0000 [id=42]  FINE  c.amazon.jenkins.ec2fleet.EC2FleetCloud: ci-jenkins-executor--integration-tests-spot [ integration-tests spot disable-resubmit 1executors] Jenkins nodes: []
2022-02-08 16:45:42.495+0000 [id=42]  FINE  c.amazon.jenkins.ec2fleet.EC2FleetCloud: ci-jenkins-executor--integration-tests-spot [ integration-tests spot disable-resubmit 1executors] Described instances: []
2022-02-08 16:45:42.495+0000 [id=42]  FINE  c.amazon.jenkins.ec2fleet.EC2FleetCloud: ci-jenkins-executor--integration-tests-spot [ integration-tests spot disable-resubmit 1executors] Fleet instances: []
2022-02-08 16:45:42.392+0000 [id=42]  FINE  c.amazon.jenkins.ec2fleet.EC2FleetCloud: ci-jenkins-executor--integration-tests-spot [ integration-tests spot disable-resubmit 1executors] start cloud com.amazon.jenkins.ec2fleet.EC2FleetCloud@26e970e3
2022-02-08 16:45:41.234+0000 [id=41]  FINE  c.a.j.ec2fleet.NoDelayProvisionStrategy: Provisioning completed
2022-02-08 16:45:41.234+0000 [id=41]  FINE  c.a.j.ec2fleet.NoDelayProvisionStrategy: label [integration-tests&&spot&&disable-resubmit]: currentDemand is less than 1, not provisioning
2022-02-08 16:45:41.234+0000 [id=41]  FINE  c.a.j.ec2fleet.NoDelayProvisionStrategy: label [integration-tests&&spot&&disable-resubmit]: currentDemand -7 availableCapacity 8 (availableExecutors 0 connectingExecutors 0 plannedCapacitySnapshot 8 additionalPlannedCapacity 0)
2022-02-08 16:45:32.506+0000 [id=41]  FINE  c.amazon.jenkins.ec2fleet.EC2FleetCloud: ci-jenkins-executor--integration-tests-spot [ integration-tests spot disable-resubmit 1executors] setting stats
2022-02-08 16:45:32.506+0000 [id=41]  FINE  c.amazon.jenkins.ec2fleet.EC2FleetCloud: ci-jenkins-executor--integration-tests-spot [ integration-tests spot disable-resubmit 1executors] Jenkins nodes: []
2022-02-08 16:45:32.506+0000 [id=41]  FINE  c.amazon.jenkins.ec2fleet.EC2FleetCloud: ci-jenkins-executor--integration-tests-spot [ integration-tests spot disable-resubmit 1executors] Described instances: []
2022-02-08 16:45:32.505+0000 [id=41]  FINE  c.amazon.jenkins.ec2fleet.EC2FleetCloud: ci-jenkins-executor--integration-tests-spot [ integration-tests spot disable-resubmit 1executors] Fleet instances: []
2022-02-08 16:45:32.392+0000 [id=41]  FINE  c.amazon.jenkins.ec2fleet.EC2FleetCloud: ci-jenkins-executor--integration-tests-spot [ integration-tests spot disable-resubmit 1executors] start cloud com.amazon.jenkins.ec2fleet.EC2FleetCloud@26e970e3
2022-02-08 16:45:31.234+0000 [id=40]  FINE  c.a.j.ec2fleet.NoDelayProvisionStrategy: Provisioning completed
2022-02-08 16:45:31.234+0000 [id=40]  FINE  c.a.j.ec2fleet.NoDelayProvisionStrategy: label [integration-tests&&spot&&disable-resubmit]: currentDemand is less than 1, not provisioning
2022-02-08 16:45:31.234+0000 [id=40]  FINE  c.a.j.ec2fleet.NoDelayProvisionStrategy: label [integration-tests&&spot&&disable-resubmit]: currentDemand -7 availableCapacity 8 (availableExecutors 0 connectingExecutors 0 plannedCapacitySnapshot 8 additionalPlannedCapacity 0)
2022-02-08 16:45:22.476+0000 [id=37]  FINE  c.amazon.jenkins.ec2fleet.EC2FleetCloud: ci-jenkins-executor--integration-tests-spot [ integration-tests spot disable-resubmit 1executors] setting stats
```

At 18:10 the status shown `target: 0` so it looks like the plugin didn't realise that there is a build waiting for this node:
<img width="729" alt="image" src="https://user-images.githubusercontent.com/4964388/153062872-bcfba0b1-69c9-475e-bace-bb017344d63d.png">

Around 18:15 we changed minimum cluster size for this to 1, and a new node was started.

What is interesting we noticed it on 2 separate jenkinses we have. We don't recall problem like this before. 

We suspect it started to happen after migration from version 2.3.7 to 2.4.1, but we're not sure.
Also we migrated to the 2.4.1 around 21.12.2021, whereas we THINK the problem started some longer time after the upgrade and jenkins restart. Not sure though.

**To Reproduce**
I don't know. It just happens from time to time and as a result our jobs are timeouted. Looks like frequency of this problem increases from week to week.

## Environment Details

**Plugin Version?**
2.4.1

**Jenkins Version?**
2.325

**Spot Fleet or ASG?**
ASG

**Label based fleet?**
No

**Linux or Windows?**
Linux

**EC2Fleet Configuration as Code**

```
    - eC2Fleet:
        name: "ci-jenkins-executor--integration-tests-spot"
        fleet: "ci-jenkins-executor--integration-tests-spot"
        labelString: "integration-tests spot disable-resubmit 1executors"
        minSize: 0
        maxSize: 120
        maxTotalUses: 50
        numExecutors: 1
        disableTaskResubmit: true
        addNodeOnlyIfRunning: false
        alwaysReconnect: true
        cloudStatusIntervalSec: 10
        computerConnector:
          sSHConnector:
            credentialsId: "standard-runner-ubuntu-user-private-key"
            launchTimeoutSeconds: 60
            maxNumRetries: 10
            port: 22
            retryWaitTime: 15
            sshHostKeyVerificationStrategy:
              manuallyTrustedKeyVerificationStrategy:
                requireInitialManualTrust: false
        fsRoot: "/mnt/jenkins/workspaces"
        idleMinutes: 3
        initOnlineCheckIntervalSec: 15
        initOnlineTimeoutSec: 600
        noDelayProvision: true
        privateIpUsed: true
        region: "us-west-2"
        restrictUsage: true
        scaleExecutorsByWeight: false
```

**Anything else unique about your setup?**

No

**Comment by wosiu** [comment] 2022-02-08 19:55
If there is anything else I could add please let me know.

**Comment by fdaca** [comment] 2022-02-17 16:14
This can be found in logs:
```
currentDemand -1 availableCapacity 8 (availableExecutors 0 connectingExecutors 0 plannedCapacitySnapshot 8 additionalPlannedCapacity 0)
```
and
```
currentDemand is less than 1, not provisioning
```

**Comment by imuqtadir** [comment] 2022-02-17 19:23
From the limited logs you provide, I see that `plannedCapacitySnapshot=8` which means that jenkins is waiting for the instances to come up. And also ` Described instances: []` which basically means that no instances were launched/running within the fleet. I don't see the target capacity printed in the logs so I can't really point to a particular issue. There could be multiple reasons for issue to happen. 

When this happens, please check whether the target on your EC2 fleet/ASG was updated. If it was indeed updated correctly and you are not getting newer instances launched, it could mean that your chosen instance types NOT available for spot currently. I'm not sure what set of instances you have selected so expanding your instance type options could be something you should do. Other reason could be that you have a user-data script attached to your instances which is causing this huge lag for them to become available. From plugin's point of view, it is responsible for calculating correct target capacity.

If the target is not getting updated, then it probably requires additional debugging.  However, since `plannedCapacitySnapshot 8` has been updated correctly, I highly doubt this to be the case. 

Side note, we recently launched minSpareInstances as part of 2.5.0. This will always keep the set amount of instances available which avoids the provisioning time. Please see https://github.com/jenkinsci/ec2-fleet-plugin/pull/321

**Comment by fdaca** [comment] 2022-02-18 11:39
@imuqtadir Thank you for the details. We're using spot nodes with EC2 Fleet plugin. What we're observing is having `plannedCapacitySnapshot` set to a desired amount for a long time, but:
- no events to scale out on the ASG side visible
- EC2 Fleet status reporting `nodes: 0, target: 0`
- our ASG maximum capacity is high - around `120`
- our spot instance requests utilisation is within limits with a lot of room
- blocks like this take 1h+ to self-resolve 

We haven't bumped into this issue after we moved to EC2 Fleet `2.5.0` version and Jenkins `2.334` yet, which might be the possible cure (?)

**Comment by mwos-sl** [comment] 2022-03-05 11:05
@imuqtadir I don't have github persmission to reopen the issue.

But the issue is definitely still there (on 2 independent jenkinses we have), 

Plugin version: 2.5.0
Jenkins: 2.336

Behaviour exactly the same as described above. 
Pipeline is hanging for more than 1 hour on:
![image](https://user-images.githubusercontent.com/55095506/156880172-44ffa42e-d45f-4edc-8fe4-aea658669d5b.png)

while plugin says target is 0, for whole that time:
<img width="320" alt="image" src="https://user-images.githubusercontent.com/55095506/156880223-88d28864-803f-460d-9d86-cc88d06cc639.png">

Attaching logs from log recorder for this plugin:
[EC2 Fleet Plugin.log](https://github.com/jenkinsci/ec2-fleet-plugin/files/8190511/EC2.Fleet.Plugin.log)

On AWS side, ASG desired count is 0. And there are no events in Activity history for the last several hours. Last events are:
![image](https://user-images.githubusercontent.com/55095506/156880466-f7cfed21-8f34-49d4-b955-c51129e5d038.png)

**Comment by mwos-sl** [comment] 2022-03-05 11:07
I noticed it gets unstucked only when new job arrives which needs the same label. So now I observed situation that a different build started which uses the same label, and as a result "target" capacity on the plugin side has just increased to 1.

**Comment by mwos-sl** [comment] 2022-03-10 21:04
Is there anything I could help to resolve this? Like provide some extra data?

**Comment by imuqtadir** [comment] 2022-03-11 18:13
@mwos-sl Thanks for the details. This seems like a transient issue and difficult to reproduce specially since the new build with the same label is able to increment the total capacity later. How often do you see this issue happening and does it affect other labels or it is specific to a single label always? If you see a pattern that helps us reproduce the bug, it will be super helpful.

**Comment by mwos-sl** [comment] 2022-03-14 18:04
> does it affect other labels
Seems like all the labels are affected.
I'll try to gather more data with time.

**Comment by mwos-sl** [comment] 2022-04-08 11:17
I've just noticed this - the plugin says there is one node available:
![image](https://user-images.githubusercontent.com/55095506/162418162-3da9fde8-015c-4282-ba92-3dd1cde6a0f1.png)

But at the same time there are no nodes:
![image](https://user-images.githubusercontent.com/55095506/162418565-ca8a0803-37c9-46c4-b6a8-411b057eb6f2.png)

And when I run a build, I can see in console output:
<img width="371" alt="image" src="https://user-images.githubusercontent.com/55095506/162425154-a77c9260-6891-4e10-a26c-add863344400.png">

Here is relevant piece of config for this label:
```
        minSize: 0
        maxSize: 80
        maxTotalUses: 50
        minSpareSize: 1
        numExecutors: 1
        addNodeOnlyIfRunning: false
        alwaysReconnect: true
        cloudStatusIntervalSec: 10
        computerConnector:
          sSHConnector:
            credentialsId: "standard-runner-ubuntu-user-private-key"
            launchTimeoutSeconds: 60
            maxNumRetries: 3
            port: 22
            retryWaitTime: 15
            prefixStartSlaveCmd: "source /usr/bin/init-script.sh; "
            sshHostKeyVerificationStrategy:
              manuallyTrustedKeyVerificationStrategy:
                requireInitialManualTrust: false
        disableTaskResubmit: false
        fsRoot: "/mnt/jenkins/workspaces"
        idleMinutes: 3
        initOnlineCheckIntervalSec: 15
        initOnlineTimeoutSec: 600
        noDelayProvision: true
        privateIpUsed: true
        region: "us-west-2"
        restrictUsage: true
        scaleExecutorsByWeight: false
```

**Comment by mwos-sl** [comment] 2022-04-08 11:24
Logs from the plugin during this time:
```
build-jenkins-fleet-sumo-pr-spot [sumo pr spot 1executors] start cloud com.amazon.jenkins.ec2fleet.EC2FleetCloud@9e36ed5
Apr 08, 2022 11:18:33 AM FINE com.amazon.jenkins.ec2fleet.EC2FleetCloud fine
build-jenkins-fleet-sumo-pr-spot [sumo pr spot 1executors] currentSpareInstanceCount: 1 additionalSpareInstancesRequired: 0
Apr 08, 2022 11:18:33 AM FINE com.amazon.jenkins.ec2fleet.EC2FleetCloud fine
build-jenkins-fleet-sumo-pr-spot [sumo pr spot 1executors] Fleet instances: [i-07f085f6b7b04909a]
Apr 08, 2022 11:18:33 AM FINE com.amazon.jenkins.ec2fleet.EC2FleetCloud fine
build-jenkins-fleet-sumo-pr-spot [sumo pr spot 1executors] Described instances: [i-07f085f6b7b04909a]
Apr 08, 2022 11:18:33 AM FINE com.amazon.jenkins.ec2fleet.EC2FleetCloud fine
build-jenkins-fleet-sumo-pr-spot [sumo pr spot 1executors] Jenkins nodes: [**i-07f085f6b7b04909a**]
Apr 08, 2022 11:18:33 AM FINE com.amazon.jenkins.ec2fleet.EC2FleetCloud fine
build-jenkins-fleet-sumo-pr-spot [sumo pr spot 1executors] setting stats
```

I checked if `i-07f085f6b7b04909a` and indeed it exists, is running, and everything seems fine to it. I also checked that this instance was connected to jenkins at some point, and it did some work.

So it's like the plugin kinda sees the instance, but the other part of jenkins not, because it is not connected as a agent. Or something like this.

**Comment by mwos-sl** [comment] 2022-04-08 11:26
FWIW: ASG in AWS console also sees this instance, and `Desired` count is set to 1 for this ASG in AWS.

**Comment by mwos-sl** [comment] 2022-04-08 12:38
EDIT: Not true what I wrote originally above! Sorry for noise you probably got on email 😓

**Comment by xocasdashdash** [comment] 2022-06-07 08:16
So i think we've hit the same issue. Somehow Jenkins is under the impression that we have an executor with a label but then it's not showing up on the UI. 
The solution for now has been to retry the jobs (manually), which is something that we want to avoid. 

From my limited java skills it seems that the issue comes from jenkins as the data that comes in here (https://github.com/jenkinsci/ec2-fleet-plugin/blob/93a0317c0618e6f1239e46b1d2f6cfcb7673c1a7/src/main/java/com/amazon/jenkins/ec2fleet/NoDelayProvisionStrategy.java#L30) is not good. 

I'm trying to see if i can find out where this data is coming from and why does jenkins think this is the case, i'm suspecting some internal caching that once it expires the situation is fixed. 

@mwos-sl have you found a valid workaround? I'm tempted to try the straight ec2 plugin instead of this one if there're no issues there

**Comment by mwos-sl** [comment] 2022-06-07 11:23
> @mwos-sl have you found a valid workaround?

Nope, unfortunately not. The issue described here was causing serious lags on our jenkinses, so we rolled back to ec2 plugin you mentioned. We don't have any issue with ec2 plugin, except it is very poor for spot instances, and we use on-demand only there. This plugin (ec2-fleet-plugin) is waaaay better for handling spots (possibility to declare multiple spot pools).

@xocasdashdash Can you experiment with setting to false "no delay provision strategy"? Maybe the bug is there and all we need is to disable it? Unfortunately I'm not able myself to test it anymore, but I wish to go back to this plugin at some point :(

**Comment by xocasdashdash** [comment] 2022-06-07 11:58
I'll try to check it out, but it seems to be a deeper issue in how jenkins assigns jobs to labels, not much this plugin can do if that fails 😕

**Comment by wosiu** [comment] 2022-10-18 21:05
I gave one more shot with the recent release of the plugin (2.5.2), and so far it works fine!!! 🤞 
It seems @h-okon fixed the issue with: https://github.com/jenkinsci/ec2-fleet-plugin/pull/343 (many thanks!!!)
Let me soak for few weeks more and I close this ticket.

**Comment by igtsekov** [comment] 2022-10-20 06:58
I am using 2.5.2 and it still happens. :(

**Comment by mwos-sl** [comment] 2022-11-15 11:40
After some investigation, it seems that `plannedCapacitySnapshot` become drifted after configuration reloading (without jenkins restart, which is no go for us):
```
label [cse&&general]: currentDemand -3 availableCapacity 4 (availableExecutors 0 connectingExecutors 0 plannedCapacitySnapshot 4 additionalPlannedCapacity 0)
```

There was 1 job in queue at the time, that's why 
current demand = queue_size - availableCapacity = 1 - 3 = -3

It was mentioned several times in already issues which are closed. But this bug is still there.

**Comment by mwos-sl** [comment] 2022-12-13 13:56
After several days of no problem we hit an issue again. I >think< the problem starts after configuration reload.

**Comment by HDatPaddle** [comment] 2022-12-13 14:13
> After several days of no problem we hit an issue again. I >think< the problem starts after configuration reload.

Agree, it also appears to happen to us after a configuration reload. A reboot clears is.

**Comment by naorc123** [comment] 2022-12-20 08:36
Is there any planned fix for it? or maybe other workaround?
We encounter it as well but restarting Jenkins after configuration reload make no sense.

**Comment by kintarowins** [comment] 2023-01-05 15:11
I'm on 2.5.2 and been having the exact same problem. It'll go away for sometime then come back again.

**Comment by wosiu** [comment] 2023-01-05 15:53
This plugin makes jenkins unusable :( After some time there are hundreds of suspended workers, and job queue is filling up.
We had to disable this plugin :( 
@pdk27 any chances there will be some resources assigned to fix the plugin? Or is it only community driven?

Otherwise spot ec2 machines cannot be leveraged by jenkins, which is in contradiction with what AWS officially says: https://aws.amazon.com/blogs/compute/cost-optimize-your-jenkins-ci-cd-pipelines-using-ec2-spot-instances/

**Comment by pdk27** [comment] 2023-03-27 19:20
Apologies for the delay in our response. We have been operating on reduced bandwidth. We are planning to assign some resources to look into the plugin and fix long-standing open issues. Thanks for your patience!

**Comment by pd-andrew-ferguson** [comment] 2023-04-11 18:10
👋 Adding myself here as someone else who's experiencing this issue! Details as best I can:

- Plugin v2.5.2
- Jenkins v2.346.3
- Provisioning workers either hangs or is extremely delayed (5-30 mins) when requesting workers for the same build job being run multiple times
- Seems to happen more often with / possibly _only_ with our Windows instances?
- Haven't tested anything with config reload or rebooting yet, but will give them a shot

**Comment by mwos-sl** [comment] 2023-05-23 12:07
@pdk27 any updates?

**Comment by mtn-boblloyd** [comment] 2023-05-23 12:51
I wound up fixing this myself and using a custom version of the plugin.  It looks like either Jenkins changed the purpose of some of the `NodeProvisioner.StrategyState` meanings, or something else changed.  In the NoDelayProvisionStrategy.java file, I changed the functionality to get the current number of functional nodes to this:

```
final LoadStatistics.LoadStatisticsSnapshot snapshot = strategyState.getSnapshot();
        final int availableCapacity = snapshot.getOnlineExecutors() + snapshot.getConnectingExecutors() - snapshot.getBusyExecutors();

        int currentDemand = snapshot.getQueueLength() - availableCapacity;
        LOGGER.log(currentDemand < 1 ? Level.FINE : Level.INFO,
                "label [{0}]: currentDemand {1} availableCapacity {2} (onlineExecutors {3} connectingExecutors {4} busyExecutors {5} queueLength {6})",
                new Object[]{label, currentDemand, availableCapacity, snapshot.getOnlineExecutors(),
                        snapshot.getConnectingExecutors(), snapshot.getBusyExecutors(), snapshot.getQueueLength()});
```

This caused the check to find the actual number of nodes that were either already provisioned or in the process of being provisioned, and find the available capacity without busy executors.  We only use 1 executor per node, so this may not fly if you're using multiple executors (I haven't tested).

This seems to keep our nodes provisioning and scaling down regularly, and I'm happy with it for our purposes, now.

**Comment by xocasdashdash** [comment] 2023-05-23 12:58
@mtn-boblloyd can't you open a PR from your fork?

**Comment by pdk27** [comment] 2023-05-24 20:20
@mtn-boblloyd Thanks so much for your PR. I am also working on a fix for currentDemand computation. I will get in touch about it soon.

----

@mwos-sl Apologies for the delay. We have been short-staffed since the developers who maintained this plugin moved on. 

I have been looking into reproducing the scenarios detailed here and in various previous (related) issues in order get the full context. I wasn't able to reproduce it intentionally but I did come across the scenario below after running the plugin for long hours:
- 1 (sometimes more than 1 🤷‍♀️ ) active/connected node takes incoming builds and runs them successfully
- As the queue gets bigger, new instances / nodes are launched but Jenkins fails to connect to them, during which they get suspended for a while, eventually getting terminated.
- Changing plugin configurations like _noDelayProvision_ didn't seem to impact the suspended instances situation

#### Some observations: #### 
1. Agent/Slave logs on the active node showed `LinkageError while performing` (stacktrace below) with NO impact on the node's ability to take on new builds. 

<details><summary>LinkageError while performing</summary>
<p>
<img width="623" alt="image" src="https://github.com/jenkinsci/ec2-fleet-plugin/assets/3614196/f14364dc-8d4d-44b7-8463-c20756a7fd99">
</p></details>

2. After the LinkageError is logged, subsequent node connections (some of which were in the process of establishing connection) just hang <img width="31" alt="image" src="https://github.com/jenkinsci/ec2-fleet-plugin/assets/3614196/b84a72e7-a201-486e-9f18-596feccc091e">, according to their logs. Logging on the plugin side showed exceptions like `java.lang.IllegalStateException: Failed to provision node. Could not connect to node 'i-
XXXXX' before timeout` or `java.io.IOException: Agent failed to connect, even though the launcher didn't report it. See the log output for details.` after which new instance was launched to keep up with the demand, and this cycle repeated.

3. The logs for suspended nodes would hang at different stages in the log. So I made sure that I was able to SSH into the new EC2 instance and also check for java version - this was not a problem. 

#### Explanation: ####
This is the only explanation I could think of. Please share thoughts if any. The combination of things below seems to be the problem.
1. Jenkins being unable to connect to new capacity + 
2. Extended time when connections are attempted without luck(depends on various configurations like number of retries, wait time between retries, timeout, etc) + 
3. `plannedCapacitySnapshot` being decremented ONLY after the connection to node is established or timeout ([code](https://github.com/jenkinsci/ec2-fleet-plugin/blob/master/src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetOnlineChecker.java#L80)) + 
4. Available capacity computation double counting executors for such (connecting) nodes with `connectingExecutors` (because of this the `availableCapacity` could differ wildly from reality, esp. when huge number of nodes are affected)

#### Fix that seemed to have worked for me: ####
[LinkageError](https://issues.jenkins.io/browse/JENKINS-62006) was [fixed](https://github.com/jenkinsci/jenkins/pull/5367) in [Jenkins 2.277.2](https://github.com/jenkins-infra/release/issues/140). I upgraded to Jenkins 2.277.2 and I have not come across the above suspended nodes situation since. 

@mwos-sl Looks like you are running a more recent version of Jenkins than 2.277.2? Have you seen different reasons why Jenkins might not be able to connect to the nodes? Is there a way for you to test with Jenkins version 2.277.2?
FYI, the nodes that are suspended have `shouldAcceptTasks` set to false which happens when the plugin attempts to terminate the instance ([code](https://github.com/jenkinsci/ec2-fleet-plugin/blob/master/src/main/java/com/amazon/jenkins/ec2fleet/EC2RetentionStrategy.java#L66)). 

I am working on fixing the computations. 
In the mean time, we will be upgrading the minimum Jenkins version for the plugin.

**Comment by ikaakkola** [comment] 2023-05-26 10:44
To clear `plannedCapacitySnapshot` (Technically these are PlannedNode instances in the NodeProvisioner, [here](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/slaves/NodeProvisioner.java#L139)) you can use a Groovy script through the Script Console.

Once you do this, scaling will again work for a while, until you accumulate enough "pending launches", causing `plannedCapacitySnapshot` to grow. When `plannedCapacitySnapshot` grows, the plugin will only scale up when there are *more* items in queue than there are "pending launches" stuck..


**List and optionally delete pending launches for all labels**
```
// If set to true, all pending launches are deleted
def deletePending = false;

for (label in Jenkins.instance.getLabels()) {
  println("Label " + label.name);
  println("   Load statistics: " + label.loadStatistics.computeSnapshot());
  println("   Nodeprovisioner state: " + label.nodeProvisioner.provisioningState);
  println("   Nodeprovisioner pending launches:");
  for (launch in label.nodeProvisioner.pendingLaunches) {
    println("      pending launch: " + launch.displayName + ", hashCode=" + launch.hashCode());
    if (deletePending) {
      println("      -> terminating!");
      launch.future.setException(new java.lang.RuntimeException("Terminating pending launch!"));
    } 
  }
  println("");
}
```

**Comment by pdk27** [comment] 2023-05-26 13:37
@ikaakkola Thats correct! It makes sense to include planned nodes in available capacity to avoid over provisioning. 

The plugin (specifically [this class)](https://github.com/jenkinsci/ec2-fleet-plugin/blob/master/src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetOnlineChecker.java#L80) controls when the planned nodes' futures are resolved - after Jenkins is able to connect to the node successfully or if that attempt times out. 
In the scenario I described above I saw that Jenkins would connect to an nodes successfully until the LinkageError occurred, after which subsequent attempts to connect to new nodes would just hang and timeout. Hence [this PR to upgrade minimum Jenkins version](https://github.com/jenkinsci/ec2-fleet-plugin/pull/368). 

What version of Jenkins are you running? Do you see any errors in agent logs?

**Comment by ikaakkola** [comment] 2023-05-26 13:40
@pdk27 we are currently on ancient versions, hence I did not add my findings here. Waiting to update to latest versions of Jenkins and the plugin and if there still are 'pending launches' that do not get completed (either done, cancelled or due to an exception) I'll dig deeper. Just wanted to share the workaround we currently use (clear the pending launches manually every now and then) which doesn't need a Jenkins restart.

(For the record, we are not seeing LinkageErrors)

**Comment by pdk27** [comment] 2023-06-01 22:43
Opened a discussion in the release [2.6.0](https://github.com/jenkinsci/ec2-fleet-plugin/discussions/372) which includes some fixes/ other changes, after which I don't see lag in provisioning in my environment. Please share details relevant to the release in the discussion.

**Comment by pdk27** [comment] 2023-06-28 19:07
@wosiu I was finally able to reproduce this issue and here is what I think is happening: 
1. Your maxTotalUses is set to 50, let's say your instances finish 50 builds and are scheduled for termination. i.e. suspended.
2. A cloud config change is initiated, leading to:
    - recreation of EC2FleetCloud object - hence loosing state like `instanceIdsToTerminate` **(problem#1)** 
3. [EC2RetentionStrategy](https://github.com/jenkinsci/ec2-fleet-plugin/blob/master/src/main/java/com/amazon/jenkins/ec2fleet/EC2RetentionStrategy.java) checks for instances to terminate when idle but this doesn't terminate the suspended instances because:
    - it only tracks 2 cases: hasExcessCapacity and idleForTooLong. See other cases [here]. **(problem#2)**(https://github.com/jenkinsci/ec2-fleet-plugin/blob/master/src/main/java/com/amazon/jenkins/ec2fleet/EC2AgentTerminationReason.java). 
    - My suspicion is that the buggy cloud object reassignments might be the reason why idle time is not respected (should be fixed with https://github.com/jenkinsci/ec2-fleet-plugin/issues/360) **(problem#3)**
4. suspended nodes remain hanging

Fixes: 
-  **problem#1** & **problem#2**: https://github.com/jenkinsci/ec2-fleet-plugin/pull/376 (specifically [this commit](https://github.com/jenkinsci/ec2-fleet-plugin/pull/376/commits/261964d99a30618e33b9bb1c7a571381f8da7c31))
See details and integration test result [here](https://github.com/jenkinsci/ec2-fleet-plugin/pull/376#issue-1777665713).
- **problem#3**: WIP

**Closed** 2023-07-17 21:55 UTC
Labels: bug
