### ISSUE TITLE
New nodes get I/O error and disconnect at ssh timeout

### ISSUE THREAD

**Issue by jimcooley** [jenkinsci/ec2-fleet-plugin#41] opened 2018-10-02 16:16 UTC
When the ec2-fleet-plugin adds new spotfleet instances as Jenkins nodes using the Launcher selection of "Launch agent agents via SSH", the nodes all connect just fine, but some percentage of them disconnect with a SEVERE I/O error shortly after launch.  The I/O error happens at exactly the configured "Connection Timeout in Seconds" from launch.   When reconnected after that, they have no problems.

I have not confirmed, but I think this only happens when "Max Idle Minutes Before Scaledown" is set (attaching the IdleRetentionStrategy to the node).

Here's the sequence from the logs with the default ssh connection timeout of 210 seconds:
```
15:01:11.832 - INFO: Found new instances from fleet (ec2-fleet test): [<snip>, i-08db665d464785aec, <snip>]
15:01:21.966 - INFO: Idle Retention initiated
15:01:21.967 - INFO: Attempting to reconnect i-08db665d464785aec
15:01:56.067 - SSH Launch of i-08db665d464785aec on 10.21.131.211 completed in 34,083 ms
15:04:51.990 - SEVERE: I/O error in channel i-08db665d464785aec
```

**Comment by jimcooley** [comment] 2018-10-02 20:30
PR #42 doesn't resolve this issue.  Perhaps it is an issue with the ssh-slaves-plugin or perhaps this ec2-fleet-plugin is just missing an integration point with that ssh-slaves-plugin.

Here's the latest failure in my logs (once again with the 210 second default for `Max Idle Minutes Before Scaledown`):
```
14:14:04.774 - INFO: Found new instances from fleet (ec2-fleet test): [i-00e94fb007d25365c]
14:14:04.856 - INFO: Connecting to instance: i-00e94fb007d25365c
14:14:56.699 - SSH Launch of i-00e94fb007d25365c on 10.21.129.136 completed in 51,837 ms
14:17:34.864 - INFO: I/O error in channel i-00e94fb007d25365c
```
The slave log has the following (there's a 2 hour timezone difference from the timestamps above):
```
[10/02/18 12:14:52] [SSH] Checking java version of java
[10/02/18 12:14:53] [SSH] java -version returned 1.8.0_181.
[10/02/18 12:14:53] [SSH] Starting sftp client.
[10/02/18 12:14:53] [SSH] Remote file system root /mnt/encrypted/jenkins-home does not exist. Will try to create it...
[10/02/18 12:14:53] [SSH] Copying latest remoting.jar...
[10/02/18 12:14:53] [SSH] Copied 776,717 bytes.
Expanded the channel window size to 4MB
[10/02/18 12:14:53] [SSH] Starting agent process: cd "/mnt/encrypted/jenkins-home" && java  -jar remoting.jar -workDir /mnt/encrypted/jenkins-home
Oct 02, 2018 7:14:54 PM org.jenkinsci.remoting.engine.WorkDirManager initializeWorkDir
INFO: Using /mnt/encrypted/jenkins-home/remoting as a remoting work directory
Both error and output logs will be printed to /mnt/encrypted/jenkins-home/remoting
<===[JENKINS REMOTING CAPACITY]===>channel started
Remoting version: 3.27
This is a Unix agent
Evacuated stdout
Agent successfully connected and online
ERROR: Connection terminated
java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2681)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3156)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:862)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
	at hudson.remoting.Command.readFrom(Command.java:140)
	at hudson.remoting.Command.readFrom(Command.java:126)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:36)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
Caused: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
ERROR: Socket connection to SSH server was lost
java.net.SocketTimeoutException: The connect timeout expired
	at com.trilead.ssh2.Connection$1.run(Connection.java:762)
	at com.trilead.ssh2.util.TimeoutService$TimeoutThread.run(TimeoutService.java:91)
Slave JVM has not reported exit code before the socket was lost
[10/02/18 12:17:34] [SSH] Connection closed.
```

I'm trying to narrow down what can be happening to produce this.
Perhaps the `c.connect(false)` from `IdleRetentionStrategy.start()` (and before that the `c.tryReconnect()` from `IdleRetentionStrategy.check()`) is being undermined by `jenkins.addNode(slave)` in `EC2FleetCloud.addNewSlave()` or vice versa.

**Comment by stibi** [comment] 2018-10-02 20:38
Interesting. I have never seen this problem on our environment…good to know.

We have our piece of fun too, quite often an agent dies with `Caused: java.io.IOException: Unexpected termination of the channel`, then usually reconnects, but that already have affected a build, so…it is a trouble. Pretty common troubles, as it seems from reported jira issues. I'm trying to find oud the root cause, not much luck so far.

Fingers crossed for both of us.

**Comment by jimcooley** [comment] 2018-10-04 16:30
I found another reference to this issue (see the latest comments by Eugene): https://issues.jenkins-ci.org/browse/JENKINS-48955

**Comment by timvanderkooi** [comment] 2018-10-04 18:19
> Interesting. I have never seen this problem on our environment…good to know.
> 
> We have our piece of fun too, quite often an agent dies with `Caused: java.io.IOException: Unexpected termination of the channel`, then usually reconnects, but that already have affected a build, so…it is a trouble. Pretty common troubles, as it seems from reported jira issues. I'm trying to find oud the root cause, not much luck so far.
> 
> Fingers crossed for both of us.

We've experienced this issue as well. Very hard to track down the cause of the issue or recreate it.

**Comment by stibi** [comment] 2018-10-04 18:31
@timvanderkooi have you solved it eventually?

**Comment by timvanderkooi** [comment] 2018-10-04 18:41
It's not as noticeable as before. I thought it may have had something to do with our networking since we run Jenkins on-prem and some of our builds slaves on the cloud with this plugin. I adjusted the ssh_config on our Jenkins server to use ServerAliveInterval and ServerAliveCountMax so that any interruption to the SSH connection would not terminate immediately. We also don't run a lot of executors on a given machine and we don't run long running builds on those slaves, so it hasn't been that much of a make or break issue for us when it does occur.

**Comment by jimcooley** [comment] 2018-10-04 22:15
I can't yet force a reproduction of this issue, but we encounter it daily.  Whenever our job queue builds up and the plugin increases the spotfleet request instance number, several new instances come online and a fraction of those hit this error.

I think something is going wrong with the trilead connection timeout.  For some reason, successful connections don't always stop the timeoutHandler from hitting the time limit and executing the connection killing code here:
https://github.com/jenkinsci/trilead-ssh2/blob/master/src/com/trilead/ssh2/Connection.java#L762

The SSHLauncher piece that calls that trilead code is here:
 https://github.com/jenkinsci/ssh-slaves-plugin/blob/master/src/main/java/hudson/plugins/sshslaves/SSHLauncher.java#L1176

**Comment by jimcooley** [comment] 2018-10-04 22:19
Since it is a problem with the trilead timeoutHandler, I'm going to try to work around this issue by increasing the "Connection Timeout in Seconds" to a massive number and see if that stabilizes my Jenkins environment.  The drawback to this approach is that the connection attempt could hang indefinitely.  That seems preferable to a rogue asynchronous process killing my builds by cutting the ssh connection.

**Comment by stibi** [comment] 2018-10-09 08:52
@jimcooley what/where is this "Connection Timeout in Seconds" option you are referring?

**Comment by stibi** [comment] 2018-10-09 14:01
:man_facepalming: nevermind, I get it now, it's in the cloud configuration section of the plugin configuration

**Comment by jimcooley** [comment] 2018-10-09 14:12
@stibi - I just about to answer 😉

Just in case anyone else reads this and has the same question:
The "Connection Timeout in Seconds" is an advanced option that is available when selecting the "Launch agents via ssh" options as the "Launcher" in the "Spot Fleet Configuration".

Here's a screenshot:
<img width="992" alt="connection_timeout_configuration" src="https://user-images.githubusercontent.com/19278582/46675097-50c51080-cba3-11e8-9125-df50dc1fb7df.png">

**Comment by stibi** [comment] 2018-10-12 06:35
Looks like setting the `"Connection Timeout in Seconds"` to a high number (6000 in our case) made the trick. It looks much more stable now. I have to dig to the code, I'd like to understand the root cause.

**Comment by thedonvaughn** [comment] 2018-10-15 16:10
We are having the same issue.  It happens daily, but only on the first build of a new EC2 instance.   After a fail build, the agent re-connects to the EC2 instance and all subsequent builds work fine.    I will try to increase `Connection Timeout in Seconds` to see if it is a viable work around.

**Comment by stibi** [comment] 2018-10-15 16:28
@thedonvaughn For us it did a great job. I left a comment [here](https://github.com/jenkinsci/ec2-fleet-plugin/pull/42#issuecomment-429219430), describing the situatation.

**Comment by thedonvaughn** [comment] 2018-10-16 01:43
Indeed upping the timeout to an insane amount and I added "docker info &&" to Prefix command works like a charm.  Thanks for the work around!

**Comment by glavoie** [comment] 2018-11-15 03:09
We just found out that we are having this issue after we upgraded the plugin to version 1.1.8. After some testing, I can reproduce the problem at will by playing with the target capacity of the spot request directly in the AWS console.

Our configuration is set to shutdown IDLE nodes after 5 minutes. Our building pattern makes our fleet target capacity vary a lot during the day. Apparently, the retry behavior that was removed in #42 was what made scaling up new nodes work "properly". The disconnection after 2 minutes (connect timeout) still occurs, but it reconnects permanently afterward. 

With the removal of the retry behavior, scaling up new nodes just doesn't work at all. Moreover, if the job queue becomes empty after a "bad" node was scaled up, the "good" node gets terminated when the target capacity is reduced after 5 minutes, blocking our whole Jenkins instance from building anything...

For now, we're reverting to 1.1.7.

**Comment by bertjwregeer** [comment] 2018-11-15 23:14
My executors are running a cloud-init script that sets them up (installs docker + openjdk and adds the Jenkins user)... depending on how fast the apt mirrors are this can take 10 seconds to 60 seconds.

By this time the ec2-fleet plugin has already added the executor to the list and is attempting to connect to it. However instead of attempting to reconnect it will fail and hang. I have set the connection timeout to 20 seconds, and the retries to 120 with a 5 second wait between retries, but it never retries.

I am not seeing the disconnect behaviour seen above though because of the low timeout.

This means that the ec2-fleet will continue to scale up, all the way to the max cluster size with all the jobs waiting in the queue for a spot, with all nodes marked offline.

I've created a new Job DSL based jenkins job with the following script:

```
for (aSlave in hudson.model.Hudson.instance.slaves) {
  println('====================');
  println('Name: ' + aSlave.name);
  println('\tcomputer.isOffline: ' + aSlave.getComputer().isOffline());
  println('\tcomputer.countBusy: ' + aSlave.getComputer().countBusy());
  if (aSlave.getComputer().isOffline()) {
    println('\tShutting down node!!!!');
    aSlave.getComputer().doDoDelete();
  }
}
```

This is run every 4 minutes using the cron feature from Jenkins.

This will loop through and remove old failed instances (which Amazon has hard killed and the ec2-fleet plugin failed to clean up), and will also remove the current booted nodes that Jenkins is not connecting to.

Once the nodes are removed the ec2-fleet notices that they are gone and will automatically re-create the nodes, at which point the SSH launcher will launch successfully, and builds will start flowing.

This is new behaviour since 1.1.8, in 1.1.7 the retry would eventually succeed in connecting to the ec2-fleet executor that was brought up.

**Comment by bertjwregeer** [comment] 2018-11-16 20:21
This is the error I am seeing to the hosts that are never retried:

```
SSHLauncher{host='10.50.10.252', port=22, credentialsId='aaf2ee5e-32bd-4675-9793-0570922f9c66', jvmOptions='', javaPath='', prefixStartSlaveCmd='', suffixStartSlaveCmd='', launchTimeoutSeconds=5, maxNumRetries=120, retryWaitTime=2, sshHostKeyVerificationStrategy=hudson.plugins.sshslaves.verifiers.ManuallyTrustedKeyVerificationStrategy, tcpNoDelay=true, trackCredentials=true}
[11/16/18 20:19:40] [SSH] Opening SSH connection to 10.50.10.252:22.
Connection refused (Connection refused)
SSH Connection failed with IOException: "Connection refused (Connection refused)", retrying in 2 seconds.  There are 120 more retries left.
Connection refused (Connection refused)
SSH Connection failed with IOException: "Connection refused (Connection refused)", retrying in 2 seconds.  There are 119 more retries left.
Connection refused (Connection refused)
SSH Connection failed with IOException: "Connection refused (Connection refused)", retrying in 2 seconds.  There are 118 more retries left.
ERROR: null
java.util.concurrent.CancellationException
	at java.util.concurrent.FutureTask.report(FutureTask.java:121)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at hudson.plugins.sshslaves.SSHLauncher.launch(SSHLauncher.java:904)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:294)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[11/16/18 20:19:45] Launch failed - cleaning up connection
[11/16/18 20:19:45] [SSH] Connection closed.
```

**Comment by jimcooley** [comment] 2018-11-19 22:07
@bertjwregeer - It sounds like it might be worthwhile to have an "Always try to reconnect to offline nodes" option in the plugin since you were relying on that functionality.  I'll look into what it would take to add that.

In the meanwhile, I might have a workaround for you.  What do you think about setting the connection timeout to an insanely high value (I use 1209600) and adding a "Prefix Start Agent Command" that waits to complete until the cloud-init script is done.

I'm thinking something like:
`Prefix Start Agent Command`: `until /bin/test -f /tmp/init-complete; do sleep 1; done && ` (note the trailing space. It is important.)
Where the last thing that the cloud-init script does is `touch /tmp/init-complete`

**Comment by jimcooley** [comment] 2018-11-19 22:21
@bertjwregeer - Once #40 makes it to the next plugin release, you shouldn't need the DSL cron job that runs `aSlave.getComputer().doDoDelete();`.

I needed something similar until that code was able to successfully manage the _offboarding_ of terminated/stopped/missing spotfleet nodes. 

Actually, I still have to run the following in a cron even with the code from #40 and #42:
```
import jenkins.model.Jenkins

stage ('spotfleet_node_cleanup') {
  for(c in Jenkins.instance.computers) {
    def n = c.node
    if (n == null) {
      if (c.isOffline()) {
        println "${c.name} offline"
        for (e in c.executors) {
          println "${e.number}: ${e.name}"
          e.doStop()
        }
      }
    }
  }
  println "done"
}
```
This workaround kills threads that are still running on nodes that have been deleted with `jenkins.removeNode(n)`.  This seems like a bug to have zombie threads running on removed nodes, but I haven't filed anything yet or tracked it down.

**Comment by bertjwregeer** [comment] 2018-11-20 00:51
@jimcooley:

Jenkins can't SSH to the node until cloud-init is complete.

So the work-around of adding a 

```
I'm thinking something like:
Prefix Start Agent Command: until /bin/test -f /tmp/init-complete; do sleep 1; done && (note the trailing space. It is important.)
Where the last thing that the cloud-init script does is touch /tmp/init-complete
```

would not work, as it is cloud-init that adds the Jenkins user + SSH key as the last thing it does. That is why SSH retrying to connect instead of just dying and doing nothing is so important to me.

Why not have Jenkins login as the `ec2-user` or `ubuntu` instead? Because of userid requirements and the way we package our software. It is expected that this is done under a userid of 999 and groupid of 997. Those are the same userid/groupid that the master runs under and matching that in our Docker containers is the easiest way to know we have a reproducible build. vs using userid 1000 or 1001 (depending on the AMI and what the `ubuntu`/`ec2-user` is created with).

**Comment by bertjwregeer** [comment] 2018-11-20 00:52
In reference to `doStop()`, I opened another ticket for that: https://github.com/jenkinsci/ec2-fleet-plugin/issues/45

A `doStop()` is going to be a nice work-around rather than waiting for them to timeout, but I would prefer if those jobs were just kicked again.

**Comment by glavoie** [comment] 2018-11-20 16:04
@jimcooley I haven't tried the long timeout but did try to play with the timeout value to see the effect. It doesn't appear anyway like a very good long term solution to me.

I would definitely prefer a "Always try to reconnect to offline nodes" option.

**Comment by glavoie** [comment] 2018-11-20 19:46
@jimcooley, I'm still digging but I think you are very close with your thought about the handling of the TimeoutHandler (https://github.com/jenkinsci/ec2-fleet-plugin/issues/41#issuecomment-427187193). 

Considering the following log:
```[11/20/18 19:22:59] [SSH] Opening SSH connection to 10.103.8.216:22.
Connection refused (Connection refused)
SSH Connection failed with IOException: "Connection refused (Connection refused)", retrying in 15 seconds.  There are 10 more retries left.
Connection refused (Connection refused)
SSH Connection failed with IOException: "Connection refused (Connection refused)", retrying in 15 seconds.  There are 9 more retries left.
Connection refused (Connection refused)
SSH Connection failed with IOException: "Connection refused (Connection refused)", retrying in 15 seconds.  There are 8 more retries left.
Connection refused (Connection refused)
SSH Connection failed with IOException: "Connection refused (Connection refused)", retrying in 15 seconds.  There are 7 more retries left.
[11/20/18 19:24:14] [SSH] The SSH key with fingerprint 38:e3:9b:7d:5b:5e:05:85:db:62:b0:2f:bb:02:0a:ca has been automatically trusted for connections to this machine.
[11/20/18 19:24:14] [SSH] Authentication successful.
...
Agent successfully connected and online
ERROR: Connection terminated
java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2681)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3156)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:862)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
	at hudson.remoting.Command.readFrom(Command.java:140)
	at hudson.remoting.Command.readFrom(Command.java:126)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:36)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
Caused: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
ERROR: Socket connection to SSH server was lost
java.net.SocketTimeoutException: The connect timeout expired
	at com.trilead.ssh2.Connection$1.run(Connection.java:762)
	at com.trilead.ssh2.util.TimeoutService$TimeoutThread.run(TimeoutService.java:91)
Slave JVM has not reported exit code before the socket was lost
[11/20/18 19:26:29] [SSH] Connection closed.
```

My current feeling is that that TimeoutHandler does get successfully cleared up upon a successful connection, but the different TimeoutHandlers created from the earlier failed connection attempts are not cleared at all in the IOException catch block: https://github.com/jenkinsci/trilead-ssh2/blob/2029d5b5284b1694b0e2798c24b341c4ae0502da/src/com/trilead/ssh2/Connection.java#L739

Since the `connection` object gets reused for the retries, any leftover TimeoutHandler can kill the connection after a successful attempt: https://github.com/jenkinsci/ssh-slaves-plugin/blob/0451b9bf1ebba57c4a80858eaaa48f3250e44709/src/main/java/hudson/plugins/sshslaves/SSHLauncher.java#L1175

**Comment by glavoie** [comment] 2018-11-20 20:15
Considering the `kex` timeout is set to the same value as the `connect` timeout here: https://github.com/jenkinsci/ssh-slaves-plugin/blob/0451b9bf1ebba57c4a80858eaaa48f3250e44709/src/main/java/hudson/plugins/sshslaves/SSHLauncher.java#L1184

I'm getting some sort of "success" (with 1.1.7) when setting a low connect timeout (25 secs) and a higher retry timeout (30 secs). For some reason, likely because the execution of the TimeoutHandler which likely breaks the `connection` object, the retry mechanism of `SSHLauncher` is not exactly the mechanism doing the retry attempt. I'm getting the following error in-between connection attempts: 
```ERROR: null
java.util.concurrent.CancellationException
	at java.util.concurrent.FutureTask.report(FutureTask.java:121)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at hudson.plugins.sshslaves.SSHLauncher.launch(SSHLauncher.java:904)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:294)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[11/20/18 20:05:24] Launch failed - cleaning up connection
[11/20/18 20:05:24] [SSH] Connection closed.```

**Comment by jimcooley** [comment] 2018-11-20 20:40
@glavoie - I was also exploring whether or not some sort of `synchronize` or thread lock could be preventing the TimeoutHandler from getting the message that the connection was successful, but didn't get any closer to a solution.

Thanks for the extra debugging information.  I'll see if I can get any further with that new information.  Let me know if you find anything else that you think would be useful in tracking this one down.

I've been working on the alwaysReconnect option, and I think I'm close.
https://github.com/jimcooley/ec2-fleet-plugin/tree/always-reconnect-option

**Comment by glavoie** [comment] 2018-11-20 21:03
Someone is actually working on the messy synchronization: https://github.com/jenkinsci/trilead-ssh2/pull/35

Tested 1.1.8 again with my workaround attempt and without your retry mechanism, it doesn't work at all.

I will try proper error handing in 
https://github.com/jenkinsci/trilead-ssh2/blob/2029d5b5284b1694b0e2798c24b341c4ae0502da/src/com/trilead/ssh2/Connection.java#L739 and report back.

**Comment by jimcooley** [comment] 2018-11-20 21:57
https://github.com/jenkinsci/trilead-ssh2/pull/35 looks very promising.

**Comment by jimcooley** [comment] 2018-11-20 23:52
@glavoie and @bertjwregeer - I've submitted a PR to add the `Always Reconnect` option.
#46 

Do either or both of you have the resources to review and/or test out the changes before we ping @schmutze about merging?

**Comment by glavoie** [comment] 2018-11-21 14:11
So, I create the following PR which seems to fix the issue: https://github.com/jenkinsci/trilead-ssh2/pull/36

I don't get any disconnection after that, with the following log:
```
Connection refused (Connection refused)
SSH Connection failed with IOException: "Connection refused (Connection refused)", retrying in 15 seconds.  There are 10 more retries left.
Connection refused (Connection refused)
SSH Connection failed with IOException: "Connection refused (Connection refused)", retrying in 15 seconds.  There are 9 more retries left.
Connection refused (Connection refused)
SSH Connection failed with IOException: "Connection refused (Connection refused)", retrying in 15 seconds.  There are 8 more retries left.
Connection refused (Connection refused)
SSH Connection failed with IOException: "Connection refused (Connection refused)", retrying in 15 seconds.  There are 7 more retries left.
[11/21/18 13:36:29] [SSH] The SSH key with fingerprint ae:22:af:b1:8a:5e:71:6c:0a:48:79:e1:b0:73:54:26 has been automatically trusted for connections to this machine.
[11/21/18 13:36:29] [SSH] Authentication successful.
... [Printing environment details]
Nov 21, 2018 1:36:29 PM org.jenkinsci.remoting.engine.WorkDirManager initializeWorkDir
INFO: Using /var/lib/jenkins/remoting as a remoting work directory
Both error and output logs will be printed to /var/lib/jenkins/remoting
<===[JENKINS REMOTING CAPACITY]===>channel started
... [More environment details]
slave setup done.
Nov 21, 2018 1:36:34 PM org.jenkinsci.remoting.util.AnonymousClassWarnings warn
WARNING: Attempt to (de-)serialize anonymous class org.jenkinsci.plugins.envinject.EnvInjectComputerListener$2; see: https://jenkins.io/redirect/serialization-of-anonymous-classes/
Agent successfully connected and online
... [Following error is when the plugin scales down the fleet size and the node actually dies]
ERROR: Connection terminated
java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2681)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3156)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:862)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
	at hudson.remoting.Command.readFrom(Command.java:140)
	at hudson.remoting.Command.readFrom(Command.java:126)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:36)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
Caused: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
ERROR: Socket connection to SSH server was lost
java.io.IOException: Cannot read full block, EOF reached.
	at com.trilead.ssh2.crypto.cipher.CipherInputStream.getBlock(CipherInputStream.java:81)
	at com.trilead.ssh2.crypto.cipher.CipherInputStream.read(CipherInputStream.java:108)
	at com.trilead.ssh2.transport.TransportConnection.receiveMessage(TransportConnection.java:232)
	at com.trilead.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:706)
	at com.trilead.ssh2.transport.TransportManager$1.run(TransportManager.java:502)
	at java.lang.Thread.run(Thread.java:748)
Slave JVM has not reported exit code before the socket was lost
[11/21/18 13:42:06] [SSH] Connection closed.
```

**Comment by glavoie** [comment] 2018-11-21 15:29
@jimcooley tested your branch with the Always Reconnect option and it appears to work as expected. When used with my PR for `trilead` I don't see anymore the disconnection (connect timeout). 

I still have a random error, but this one is on our side. We also use a cloud-init script that setups ephemeral storage. When SSHd gets started, but the script hasn't completed, Jenkins may try to connect the slave before the permissions are set correctly on the target folder causing the following error:
```[11/21/18 15:21:40] [SSH] Copying latest remoting.jar...
java.io.IOException: Could not copy remoting.jar into '/var/lib/jenkins' on agent
	at hudson.plugins.sshslaves.SSHLauncher.copyAgentJar(SSHLauncher.java:1110)
	at hudson.plugins.sshslaves.SSHLauncher.access$400(SSHLauncher.java:128)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:864)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:831)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Could not copy remoting.jar to '/var/lib/jenkins/remoting.jar' on agent
	at hudson.plugins.sshslaves.SSHLauncher.copyAgentJar(SSHLauncher.java:1105)
	... 7 more
Caused by: com.trilead.ssh2.SFTPException: Permission denied (SSH_FX_PERMISSION_DENIED: The user does not have sufficient permissions to perform the operation.)
	at com.trilead.ssh2.SFTPv3Client.openFile(SFTPv3Client.java:1201)
	at com.trilead.ssh2.SFTPv3Client.createFile(SFTPv3Client.java:1074)
	at com.trilead.ssh2.SFTPv3Client.createFile(SFTPv3Client.java:1055)
	at hudson.plugins.sshslaves.SFTPClient.writeToFile(SFTPClient.java:91)
	at hudson.plugins.sshslaves.SSHLauncher.copyAgentJar(SSHLauncher.java:1095)
	... 7 more```

The Always Reconnect option covers that scenario.

**Comment by bertjwregeer** [comment] 2018-11-21 19:04
@jimcooley I am unfortunately not familiar enough with building the plugins for Jenkins, or the environment required to do so :-(.

I also don't have the time to learn with all my other responsibilities. Sadly I only come to bring issues rather than solutions :-(

**Comment by jimcooley** [comment] 2018-11-21 19:41
@bertjwregeer - No problem at all.  Thanks for flagging the issues and working through your use cases with me.

**Comment by jzila** [comment] 2018-11-21 21:33
@glavoie FYI re: your ephemeral storage problem, I've found that the following `rc.local` fixes all of those races. It runs way before cloud-init, and also addresses if an instance is stopped and restarted.

https://gist.github.com/jzila/57a973ff97cdb143963ba0bdc061e810

**Comment by glavoie** [comment] 2018-11-21 21:37
@jzila thanks for the tip. I like the idea!

**Comment by stibi** [comment] 2018-11-21 21:53
Hi guys, I will help with the testing.

Btw, is there any CI setup to have PR builds, etc?
How bad it sounds if I setup CircleCI to build a Jenkins plugin? 😁

I did that already, actually. But it's running against my fork.

I'd be happy to help here.

**Comment by bgaillard** [comment] 2019-02-22 06:45
Hi, we also encounter several problems related to this issue. This is impacting our whole team so fixing it is very important for us.

To help others understand the bug and fix it here is a an abstract of the previous conversations. 

@jimcooley and @glavoie thanks a lot for your work !

### The issue

The Trilead connection timeout in the [trilead-ssh2](https://github.com/jenkinsci/trilead-ssh2) library is not well managed, more particularly with the [`timeoutHandler`](https://github.com/jenkinsci/trilead-ssh2/blob/master/src/com/trilead/ssh2/Connection.java#L679).

### Workaroud / mitigate the issue

The following tricks have been provided by @jimcooley to mitigate the issue. Be careful because this is only a workaround and not a durable fix.

* Set a very high number in the `Connection Timeout in Seconds` setting, for example `1209600`
* (Optional) If you are running long cloud init scripts on your slaves add something like `docker info &&` in the `Prefix Start Agent Command` field

### Potential fixes

* **FIX 1** : [Always reconnect option #46](https://github.com/jenkinsci/ec2-fleet-plugin/pull/46) (release in version `1.1.9` of the plugin)
* **FIX 2** : [Connection timeout handler not cancelled when an exception occurs dur ... #36](https://github.com/jenkinsci/trilead-ssh2/pull/36)

### Installing the Trilead fixes in Jenkins (**FIX 2**)

```
cd /tmp 
git clone git@github.com:jenkinsci/trilead-api-plugin.git
git clone git@github.com:jenkinsci/trilead-ssh2.git
```

In the `trilead-api-plugin/pom.xml` file update the version of the `trilead-ssh2` plugin to `build-217-jenkins-15-SNAPSHOT` (i.e the version mentioned in the `trilead-ssh2/pom.xml`).

Then enter the following commands (the dependencies download and tests phases could be long, this is normal)

```
cd trilead-ssh2
mvn install
cd ../trilead-api-plugin
mvn install
```

Install the `trilead-api-plugin/target/trilead-api.hpi` file using the Upload Plugin options of the Advanced tab in the Plugin Manager.

I installed the **FIX 2** today, I'll let you know if the correction work in few days.

Thanks

**Comment by terma** [comment] 2019-06-24 18:05
is that issue still valid?

**Comment by jimcooley** [comment] 2019-06-24 19:57
@terma - Assuming that jenkinsci/trilead-ssh2#36 fixed the root cause, then we should be good.  That fix has made it into the current version of Trilead API plugin.

**Comment by glavoie** [comment] 2019-06-25 13:50
@terma @jimcooley I can still reproduce the issue with the latest `ssh-slaves-plugin`. While the fix has been included in `trilead-api-plugin`, I think `ssh-slaves-plugin` still uses the older version of the Trilead JAR attached to Jenkins core. 

I still haven't seen the change/fix for https://issues.jenkins-ci.org/browse/JENKINS-53468?focusedCommentId=354442&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-354442

**Comment by terma** [comment] 2019-06-25 14:45
thx for update, will keep it open

**Comment by jimcooley** [comment] 2019-06-25 15:24
@glavoie - Thanks for the clarification, and for continuing to push on the upstream projects!

**Comment by diraol** [comment] 2020-07-28 23:18
(Just as a heads up, still happening)

**Comment by imuqtadir** [comment] 2021-10-29 18:37
@LoveDuckie Can you please open a new issue along with logs and provide info around your setup? I'm closing off this issue as it is pretty old and having latest info per newer releases would be helpful

**Closed by imuqtadir** 2021-10-29 18:37 UTC
