### ISSUE TITLE
Resubmitted build uses the parameters of the last build instead of the failed build

### ISSUE THREAD

**Issue by benipeled** [jenkinsci/ec2-fleet-plugin#335] opened 2022-05-01 06:59 UTC
## Issue Details

In case of spot termination, a new build is submitted with the last build parameters

https://github.com/jenkinsci/ec2-fleet-plugin/blob/93a0317c0618e6f1239e46b1d2f6cfcb7673c1a7/src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetAutoResubmitComputerLauncher.java#L103-L106

But... in the case of multiple builds, the last one is not necessarily the build that should be rebuilt, which causes the resubmitted job uses incorrect parameters.

**To Reproduce**
1. Trigger a workflow job with parameters
2. Trigger another workflow job with parameters
3. Terminate the instance used for the 1st build - a new build should be added to the queue
4. Check the new build parameters - it will be the 2nd build parameters instead of the 1st one.

## Environment Details

**Plugin Version?**
2.5.1

**Jenkins Version?**
2.343

**Spot Fleet or ASG?**
Spot Fleet

**Label based fleet?**
Yes

**Linux or Windows?**
Linux

**Comment by sebek64** [comment] 2022-11-16 11:07
I've seen the same issue. Basically, without this being fixed, spot workers with auto-retry are usable only for non-parameterized builds. For anything more sophisticated like pull-requests checks, you cannot rely on it. Any chance this will be fixed? Or should I just provide a patch?

**Comment by sebek64** [comment] 2022-11-16 14:38
As already written in the original report, the problem is on this line:
https://github.com/jenkinsci/ec2-fleet-plugin/blob/8bfcdf4c68a828621dd3523be293c82a978c42ba/src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetAutoResubmitComputerLauncher.java#L104
One can call `getLastFailedBuild` instead of `getLastBuild`, that would work better in some cases, but it is not perfect either. To me, it seems that jenkins api doesn't provide the means to properly resubmit the failed job.

**Closed** 2023-08-23 21:37 UTC
Labels: bug, good first issue, closing soon

**Comment by benipeled** [comment] 2023-08-24 08:25
@naraharip2017, @pdk27 thanks for the work done on https://github.com/jenkinsci/ec2-fleet-plugin/commit/efbed253860c160911b51e23e7a040ee70a216ef but I believe we should reopen this issue since it's not resolved the described issue,

The `getLastFailedBuild()` fixed will work only in the case of two builds while in our case it might be 10 different builds running in parallel (maybe I should've clarified that above) and the last failure might be a later job and not the one with the spot-termination event,

In addition, in our case, spot-termination marks the pipeline as ABORTED and not FAILURE which I'm not sure if it's caught by the `getLastFailedBuild()` function,

IMO, the resubmit feature should look for the exact fail-build, gather the parameters, and trigger a new one with those parameters, WDYT?
